Profile_Config = {
    Packet = 25,

    WindowID = 17,

    SlotPosition = {
        [0]   = {X = 26,    Y = 158,   W = 37, H = 60}, --SLOT ORIGINAL WEAPON RIGHT (WEAPON)
        [1]   = {X = 149,   Y = 158,   W = 37, H = 60}, --SLOT ORIGINAL WEAPON LEFT (SHIELD)
        [2]   = {X = 88,    Y = 110,   W = 37, H = 40}, --SLOT ORIGINAL HELM
        [3]   = {X = 88,    Y = 158,   W = 37, H = 60}, --SLOT ORIGINAL ARMOR
        [4]   = {X = 88,    Y = 228,   W = 37, H = 40}, --SLOT ORIGINAL PANTS
        [5]   = {X = 26,    Y = 228,   W = 37, H = 40}, --SLOT ORIGINAL GLOVES
        [6]   = {X = 149.1, Y = 228,   W = 37, H = 40}, --SLOT ORIGINAL BOOTS
        [7]   = {X = 130,   Y = 110,   W = 57, H = 40}, --SLOT ORIGINAL WINGS
        [8]   = {X = 26,    Y = 110,   W = 37, H = 40}, --SLOT ORIGINAL PET
        [9]   = {X = 67,    Y = 158,   W = 20, H = 20}, --SLOT ORIGINAL PENDANT
        [10]  = {X = 67,    Y = 228,   W = 20, H = 20}, --SLOT ORIGINAL RING RIGHT
        [11]  = {X = 129,   Y = 228,   W = 20, H = 20}, --SLOT ORIGINAL RING LEFT

        [236] = {X = 66.9,    Y = 110,   W = 20, H = 20}, --SLOT CUSTOM DARK RAVEN
        [237] = {X = 129,   Y = 248,   W = 20, H = 20}, --SLOT CUSTOM PET AUXILIAR
        [238] = {X = 67,    Y = 197.5, W = 20, H = 20}, --SLOT CUSTOM EARRING RIGHT
        [239] = {X = 129,   Y = 197.5, W = 20, H = 20}, --SLOT CUSTOM EARRING LEFT

        [240] = {X = 26,    Y = 158,   W = 37, H = 60}, --SLOT VISUAL WEAPON RIGHT (WEAPON)
        [241] = {X = 149,   Y = 158,   W = 37, H = 60}, --SLOT VISUAL WEAPON LEFT (SHIELD)
        [242] = {X = 88,    Y = 110,   W = 37, H = 40}, --SLOT VISUAL HELM
        [243] = {X = 88,    Y = 158,   W = 37, H = 60}, --SLOT VISUAL ARMOR
        [244] = {X = 88,    Y = 228,   W = 37, H = 40}, --SLOT VISUAL PANTS
        [245] = {X = 26,    Y = 228,   W = 37, H = 40}, --SLOT VISUAL GLOVES
        [246] = {X = 149.1, Y = 228,   W = 37, H = 40}, --SLOT VISUAL BOOTS
        [247] = {X = 130,   Y = 110,   W = 57, H = 40}, --SLOT VISUAL WINGS
        [248] = {X = 26,    Y = 110,   W = 37, H = 40}, --SLOT VISUAL PET

    },

    Classe = {
        [0] = "Soul Master",
        [1] = "Blade Knight",
        [2] = "Muse Elf",
        [3] = "Magic Gladiator",
    },

    Mapa = {
        [0]  = "Lorencia",
        [1]  = "Dungeon",
        [2]  = "Devias",
        [3]  = "Noria",
        [4]  = "LostTower",
        [5]  = "Exile",
        [6]  = "Arena",
        [7]  = "Atlans",
        [8]  = "Tarkan",
        [9]  = "Devil Square",
        [10] = "Icarus",
        [11] = "Blood Castle 1",
        [12] = "Blood Castle 2",
        [13] = "Blood Castle 3",
        [14] = "Blood Castle 4",
        [15] = "Blood Castle 5",
        [16] = "Blood Castle 6",
        [17] = "Blood Castle 7",
        [18] = "Chaos Castle 1",
        [19] = "Chaos Castle 2",
        [20] = "Chaos Castle 3",
        [21] = "Chaos Castle 4",
        [22] = "Chaos Castle 5",
        [23] = "Chaos Castle 6",
        [24] = "Kalima 1",
        [25] = "Kalima 2",
        [26] = "Kalima 3",
        [27] = "Kalima 4",
        [28] = "Kalima 5",
        [29] = "Kalima 6",
        [30] = "Valley of Loren",
        [31] = "Land of Trials",
        [32] = "Devil Square",
        [33] = "Aida",
        [34] = "Crywolf Fortress",
        [35] = "Mapa 35",
        [36] = "Kalima 7",
        [37] = "Kantru",
        [38] = "Kantru 2",
        [39] = "Kantru 3",
        [40] = "Silent Map",
        [41] = "Barracks of Balgass",
        [42] = "Balgass Refuge",
        [45] = "Illusion Temple 1",
        [46] = "Illusion Temple 2",
        [47] = "Illusion Temple 3",
        [48] = "Illusion Temple 4",
        [49] = "Illusion Temple 5",
        [50] = "Illusion Temple 6",
        [51] = "Elbeland",
        [52] = "Blood Castle 8",
        [53] = "Chaos Castle 7",
        [56] = "Swamp of Calmness",
        [57] = "Raklion",
        [58] = "Raklion Boss",
        [59] = "Mapa 59",
        [60] = "Mapa 60",
        [61] = "Mapa 61",
        [62] = "Santa Village",
        [63] = "Vulcanus",
        [64] = "Coliseu",
        [65] = "Doppelganger (Double Goer)",
        [66] = "Doppelganger (Double Goer)",
        [67] = "Doppelganger (Double Goer)",
        [68] = "Doppelganger (Double Goer)",
        [69] = "Empire Fortress",
        [70] = "Empire Fortress",
        [71] = "Empire Fortress",
        [72] = "Empire Fortress",
        [73] = "Mapa 73",
        [74] = "Mapa 74",
        [75] = "Mapa 75",
        [76] = "Mapa 76",
        [77] = "Mapa 77",
        [78] = "Mapa 78",
        [79] = "LorenMarket",
        [80] = "Mapa 80",
        [81] = "Mapa 81",
        [82] = "Void",
        [83] = "Mapa 83",
        [84] = "Mapa 84",
        [85] = "Mapa 85",
        [86] = "Mapa 86",
        [87] = "Mapa 87",
        [88] = "Mapa 88",
        [89] = "Mapa 89",
        [90] = "Mapa 90",
        [91] = "Mapa 91",
        [92] = "Mapa 92",
        [93] = "Mapa 93",
        [94] = "Mapa 94",
        [95] = "Mapa 95",
        [96] = "Mapa 96",
        [97] = "Mapa 97",
        [98] = "Mapa 98",
        [99] = "Mapa 99",
        [100] = "Mapa 100",
    },

    Texts = {
        ["Eng"] = {
            [1] = "PROFILE",
            [2] = "Close",
            [3] = "%s's Inventory",
            [4] = "%s My Profile",
            [5] = "Search Character",
            [6] = "%s does not exist",
            [7] = "%s has hidden his character profile",
            [8] = "Inventory",
            [9] = "Characteristics",
            [10] = "Guild",
            [11] = "Reset:",
            [12] = "Master Reset:",
            [13] = "SD:",
            [14] = "Map:",
            [15] = "X Coordinate:",
            [16] = "Y Coordinate:",
            [17] = "Class:",
            [18] = "Level:",
            [19] = "Strength:",
            [20] = "Agility:",
            [21] = "Energy:",
            [22] = "Vitality:",
            [23] = "Statistics",
            [24] = "Location",
            [25] = "Name:",
            [26] = "Position:",
            [27] = "Show",
            [28] = "Hide",
            [29] = "Enter the desired character",
            [30] = "Your profile is now hidden",
            [31] = "Your profile is now visible",
            [32] = "Invalid character",
            [33] = "Character is offline or does not exist",
            [34] = "The character has hidden the profile",
            [35] = "Update",
            [36] = "Do you want to pay %d %s to see one time?",
            [37] = "You can't see the profile of a member of the staff",
            [39] = "%s's Visual",
            [40] = "CANCEL",
        },
        ["Por"] = {
            [1] = "PERFIL",
            [2] = "Fechar",
            [3] = "Inventário de %s",
            [4] = "%s Meu Perfil",
            [5] = "Buscar Personagem",
            [6] = "%s não existe",
            [7] = "%s escondeu o perfil do personagem",
            [8] = "Inventário",
            [9] = "Características",
            [10] = "Guild",
            [11] = "Reset:",
            [12] = "Master Reset:",
            [13] = "SD:",
            [14] = "Mapa:",
            [15] = "Coordenada X:",
            [16] = "Coordenada Y:",
            [17] = "Classe:",
            [18] = "Level:",
            [19] = "Força:",
            [20] = "Agilidade:",
            [21] = "Energia:",
            [22] = "Vitalidade:",
            [23] = "Estatísticas",
            [24] = "Localização",
            [25] = "Nome:",
            [26] = "Cargo:",
            [27] = "Mostrar",
            [28] = "Ocultar",
            [29] = "Informe o personagem desejado",
            [30] = "Seu perfil está oculto",
            [31] = "Seu perfil está visível",
            [32] = "Personagem inválido",
            [33] = "Personagem está offline",
            [34] = "O personagem ocultou o perfil",
            [35] = "Atualizar",
            [36] = "Deseja pagar %d %s para visualizar uma vez?",
            [37] = "Você não pode ver o perfil de um membro da staff",
            [38] = "Você não tem saldo suficiente para ver o perfil",
            [39] = "Visual de %s",
            [40] = "CANCELAR",
        },
        ["Spn"] = {
            [1] = "PERFIL",
            [2] = "Fechar",
            [3] = "Inventário de %s",
            [4] = "%s Meu Perfil",
            [5] = "Buscar Personagem",
            [6] = "%s não existe",
            [7] = "%s escondeu o perfil do personagem",
            [8] = "Inventário",
            [9] = "Características",
            [10] = "Guild",
            [11] = "Reset:",
            [12] = "Master Reset:",
            [13] = "SD:",
            [14] = "Mapa:",
            [15] = "Coordenada X:",
            [16] = "Coordenada Y:",
            [17] = "Classe:",
            [18] = "Level:",
            [19] = "Força:",
            [20] = "Agilidade:",
            [21] = "Energia:",
            [22] = "Vitalidade:",
            [23] = "Estatísticas",
            [24] = "Localização",
            [25] = "Nome:",
            [26] = "Cargo:",
            [27] = "Mostrar",
            [28] = "Ocultar",
            [29] = "Informe o personagem desejado",
            [30] = "Seu perfil está oculto",
            [31] = "Seu perfil está visível",
            [32] = "Personagem inválido",
            [33] = "Personagem está offline",
            [34] = "O personagem ocultou o perfil",
            [35] = "Atualizar",
            [36] = "Deseja pagar %d %s para visualizar uma vez?",
            [37] = "Você não pode ver o perfil de um membro da staff",
            [38] = "Você não tem saldo suficiente para ver o perfil",
            [39] = "Visual de %s",
            [40] = "CANCELAR",
        },
    }
}

return Profile_Config