OpenFolder("Definitions")

--[[
    this disable glow excellent and ancient!
    desabilita glow excellent e anciente!
]]--

DISABLE_EXCELLENT_ITEMS = {
--------------------------------------------------------------------------------------------------
--                                       DISABLE EXCELENTE BOX                                ----
--------------------------------------------------------------------------------------------------

    { ItemIndex = GET_ITEM_MODEL(14, 403) },

--------------------------------------------------------------------------------------------------
--                                       DISABLE EXCELENTE HELPERS                          ----
--------------------------------------------------------------------------------------------------
    { ItemIndex = GET_ITEM_MODEL(13, 200) },
    { ItemIndex = GET_ITEM_MODEL(13, 201) },
    { ItemIndex = GET_ITEM_MODEL(13, 202) },
    { ItemIndex = GET_ITEM_MODEL(13, 203) },
    { ItemIndex = GET_ITEM_MODEL(13, 204) },
    { ItemIndex = GET_ITEM_MODEL(13, 205) },
    { ItemIndex = GET_ITEM_MODEL(13, 206) },
    { ItemIndex = GET_ITEM_MODEL(13, 207) },
    { ItemIndex = GET_ITEM_MODEL(13, 208) },
    { ItemIndex = GET_ITEM_MODEL(13, 209) },
    { ItemIndex = GET_ITEM_MODEL(13, 210) },
    { ItemIndex = GET_ITEM_MODEL(13, 211) },
    { ItemIndex = GET_ITEM_MODEL(13, 212) },
    { ItemIndex = GET_ITEM_MODEL(13, 213) },
    { ItemIndex = GET_ITEM_MODEL(13, 214) },
    { ItemIndex = GET_ITEM_MODEL(13, 215) },
    { ItemIndex = GET_ITEM_MODEL(13, 216) },
    { ItemIndex = GET_ITEM_MODEL(13, 217) },
    { ItemIndex = GET_ITEM_MODEL(13, 218) },
    { ItemIndex = GET_ITEM_MODEL(13, 219) },
    { ItemIndex = GET_ITEM_MODEL(13, 220) },
    { ItemIndex = GET_ITEM_MODEL(13, 221) },
    { ItemIndex = GET_ITEM_MODEL(13, 222) },
    { ItemIndex = GET_ITEM_MODEL(13, 223) },
    { ItemIndex = GET_ITEM_MODEL(13, 224) },
    { ItemIndex = GET_ITEM_MODEL(13, 225) },
    { ItemIndex = GET_ITEM_MODEL(13, 226) },
    { ItemIndex = GET_ITEM_MODEL(13, 227) },
    { ItemIndex = GET_ITEM_MODEL(13, 228) },
    { ItemIndex = GET_ITEM_MODEL(13, 229) },
    { ItemIndex = GET_ITEM_MODEL(13, 230) },
    { ItemIndex = GET_ITEM_MODEL(13, 231) },
    { ItemIndex = GET_ITEM_MODEL(13, 232) },
    { ItemIndex = GET_ITEM_MODEL(13, 233) },
    { ItemIndex = GET_ITEM_MODEL(13, 234) },
    { ItemIndex = GET_ITEM_MODEL(13, 235) },
    { ItemIndex = GET_ITEM_MODEL(13, 236) },
    { ItemIndex = GET_ITEM_MODEL(13, 237) },
    { ItemIndex = GET_ITEM_MODEL(13, 238) },
    { ItemIndex = GET_ITEM_MODEL(13, 239) },
    { ItemIndex = GET_ITEM_MODEL(13, 240) },
    { ItemIndex = GET_ITEM_MODEL(13, 241) },
    { ItemIndex = GET_ITEM_MODEL(13, 242) },
    { ItemIndex = GET_ITEM_MODEL(13, 243) },
    { ItemIndex = GET_ITEM_MODEL(13, 244) },
    { ItemIndex = GET_ITEM_MODEL(13, 245) },
    { ItemIndex = GET_ITEM_MODEL(13, 246) },
    { ItemIndex = GET_ITEM_MODEL(13, 247) },
    { ItemIndex = GET_ITEM_MODEL(13, 248) },
    { ItemIndex = GET_ITEM_MODEL(13, 249) },
    { ItemIndex = GET_ITEM_MODEL(13, 250) },
    { ItemIndex = GET_ITEM_MODEL(13, 251) },
    { ItemIndex = GET_ITEM_MODEL(13, 252) },
    { ItemIndex = GET_ITEM_MODEL(13, 253) },
    { ItemIndex = GET_ITEM_MODEL(13, 254) },
    { ItemIndex = GET_ITEM_MODEL(13, 255) },
    { ItemIndex = GET_ITEM_MODEL(13, 256) },
    { ItemIndex = GET_ITEM_MODEL(13, 257) },
    { ItemIndex = GET_ITEM_MODEL(13, 258) },
    { ItemIndex = GET_ITEM_MODEL(13, 259) },
    { ItemIndex = GET_ITEM_MODEL(13, 260) },
    { ItemIndex = GET_ITEM_MODEL(13, 261) },
    { ItemIndex = GET_ITEM_MODEL(13, 262) },
    { ItemIndex = GET_ITEM_MODEL(13, 263) },
    { ItemIndex = GET_ITEM_MODEL(13, 264) },
    { ItemIndex = GET_ITEM_MODEL(13, 265) },
    { ItemIndex = GET_ITEM_MODEL(13, 266) },
    { ItemIndex = GET_ITEM_MODEL(13, 267) },
    { ItemIndex = GET_ITEM_MODEL(13, 268) },
    { ItemIndex = GET_ITEM_MODEL(13, 269) },
    { ItemIndex = GET_ITEM_MODEL(13, 270) },
    { ItemIndex = GET_ITEM_MODEL(13, 271) },
    { ItemIndex = GET_ITEM_MODEL(13, 272) },
    { ItemIndex = GET_ITEM_MODEL(13, 273) },
    { ItemIndex = GET_ITEM_MODEL(13, 274) },
    { ItemIndex = GET_ITEM_MODEL(13, 275) },
    { ItemIndex = GET_ITEM_MODEL(13, 276) },
    { ItemIndex = GET_ITEM_MODEL(13, 277) },
    { ItemIndex = GET_ITEM_MODEL(13, 278) },
    { ItemIndex = GET_ITEM_MODEL(13, 279) },
    { ItemIndex = GET_ITEM_MODEL(13, 280) },
    { ItemIndex = GET_ITEM_MODEL(13, 281) },
    { ItemIndex = GET_ITEM_MODEL(13, 282) },
    { ItemIndex = GET_ITEM_MODEL(13, 283) },
    { ItemIndex = GET_ITEM_MODEL(13, 284) },
    { ItemIndex = GET_ITEM_MODEL(13, 285) },
    { ItemIndex = GET_ITEM_MODEL(13, 286) },
    { ItemIndex = GET_ITEM_MODEL(13, 287) },
    { ItemIndex = GET_ITEM_MODEL(13, 288) },
    { ItemIndex = GET_ITEM_MODEL(13, 289) },
    { ItemIndex = GET_ITEM_MODEL(13, 290) },
    { ItemIndex = GET_ITEM_MODEL(13, 291) },
    { ItemIndex = GET_ITEM_MODEL(13, 292) },
    { ItemIndex = GET_ITEM_MODEL(13, 304) },
    { ItemIndex = GET_ITEM_MODEL(13, 305) },
    { ItemIndex = GET_ITEM_MODEL(13, 306) },
    { ItemIndex = GET_ITEM_MODEL(13, 307) },
    { ItemIndex = GET_ITEM_MODEL(13, 308) },
    { ItemIndex = GET_ITEM_MODEL(13, 309) },
    { ItemIndex = GET_ITEM_MODEL(13, 310) },
    { ItemIndex = GET_ITEM_MODEL(13, 311) },
    { ItemIndex = GET_ITEM_MODEL(13, 312) },
    { ItemIndex = GET_ITEM_MODEL(13, 313) },
    { ItemIndex = GET_ITEM_MODEL(13, 314) },
    { ItemIndex = GET_ITEM_MODEL(13, 315) },
    { ItemIndex = GET_ITEM_MODEL(13, 316) },
    { ItemIndex = GET_ITEM_MODEL(13, 317) },
    { ItemIndex = GET_ITEM_MODEL(13, 318) },
    { ItemIndex = GET_ITEM_MODEL(13, 319) },
    { ItemIndex = GET_ITEM_MODEL(13, 320) },
    { ItemIndex = GET_ITEM_MODEL(13, 321) },
    { ItemIndex = GET_ITEM_MODEL(13, 322) },
    { ItemIndex = GET_ITEM_MODEL(13, 323) },
    { ItemIndex = GET_ITEM_MODEL(13, 324) },
    { ItemIndex = GET_ITEM_MODEL(13, 325) },
    { ItemIndex = GET_ITEM_MODEL(13, 326) },
    { ItemIndex = GET_ITEM_MODEL(13, 327) },
    { ItemIndex = GET_ITEM_MODEL(13, 328) },
    { ItemIndex = GET_ITEM_MODEL(13, 329) },
    { ItemIndex = GET_ITEM_MODEL(13, 330) },
    { ItemIndex = GET_ITEM_MODEL(13, 331) },
    { ItemIndex = GET_ITEM_MODEL(13, 332) },
    { ItemIndex = GET_ITEM_MODEL(13, 333) },
    { ItemIndex = GET_ITEM_MODEL(13, 334) },
    { ItemIndex = GET_ITEM_MODEL(13, 335) },
    { ItemIndex = GET_ITEM_MODEL(13, 336) },
    { ItemIndex = GET_ITEM_MODEL(13, 337) },
    { ItemIndex = GET_ITEM_MODEL(13, 338) },
    { ItemIndex = GET_ITEM_MODEL(13, 339) },
    { ItemIndex = GET_ITEM_MODEL(13, 340) },
    { ItemIndex = GET_ITEM_MODEL(13, 341) },
    { ItemIndex = GET_ITEM_MODEL(13, 342) },
    { ItemIndex = GET_ITEM_MODEL(13, 343) },
    { ItemIndex = GET_ITEM_MODEL(13, 344) },
	
    { ItemIndex = GET_ITEM_MODEL(13, 349) },
    { ItemIndex = GET_ITEM_MODEL(13, 350) },
    { ItemIndex = GET_ITEM_MODEL(13, 351) },
    { ItemIndex = GET_ITEM_MODEL(13, 352) },
    { ItemIndex = GET_ITEM_MODEL(13, 353) },
    { ItemIndex = GET_ITEM_MODEL(13, 354) },
    { ItemIndex = GET_ITEM_MODEL(13, 355) },
    { ItemIndex = GET_ITEM_MODEL(13, 356) },
    { ItemIndex = GET_ITEM_MODEL(13, 357) },
    { ItemIndex = GET_ITEM_MODEL(13, 358) },
    { ItemIndex = GET_ITEM_MODEL(13, 359) },
    { ItemIndex = GET_ITEM_MODEL(13, 360) },
    { ItemIndex = GET_ITEM_MODEL(13, 361) },
    { ItemIndex = GET_ITEM_MODEL(13, 362) },
    { ItemIndex = GET_ITEM_MODEL(13, 363) },
    { ItemIndex = GET_ITEM_MODEL(13, 364) },
    { ItemIndex = GET_ITEM_MODEL(13, 365) },
    { ItemIndex = GET_ITEM_MODEL(13, 366) },
    { ItemIndex = GET_ITEM_MODEL(13, 367) },
    { ItemIndex = GET_ITEM_MODEL(13, 368) },
    { ItemIndex = GET_ITEM_MODEL(13, 369) },
	{ ItemIndex = GET_ITEM_MODEL(13, 369) },
	{ ItemIndex = GET_ITEM_MODEL(13, 370) },
	{ ItemIndex = GET_ITEM_MODEL(13, 371) },
	{ ItemIndex = GET_ITEM_MODEL(13, 372) },
	{ ItemIndex = GET_ITEM_MODEL(13, 373) },
	{ ItemIndex = GET_ITEM_MODEL(13, 374) },
	{ ItemIndex = GET_ITEM_MODEL(13, 375) },
	{ ItemIndex = GET_ITEM_MODEL(13, 376) },
	{ ItemIndex = GET_ITEM_MODEL(13, 377) },
	{ ItemIndex = GET_ITEM_MODEL(13, 378) },
	{ ItemIndex = GET_ITEM_MODEL(13, 379) },
	{ ItemIndex = GET_ITEM_MODEL(13, 380) },
	{ ItemIndex = GET_ITEM_MODEL(13, 381) },
	{ ItemIndex = GET_ITEM_MODEL(13, 382) },
	{ ItemIndex = GET_ITEM_MODEL(13, 383) },
	{ ItemIndex = GET_ITEM_MODEL(13, 384) },
	{ ItemIndex = GET_ITEM_MODEL(13, 385) },
	{ ItemIndex = GET_ITEM_MODEL(13, 386) },
	{ ItemIndex = GET_ITEM_MODEL(13, 387) },
	{ ItemIndex = GET_ITEM_MODEL(13, 388) },
	{ ItemIndex = GET_ITEM_MODEL(13, 389) },
	{ ItemIndex = GET_ITEM_MODEL(13, 390) },
	{ ItemIndex = GET_ITEM_MODEL(13, 391) },
	{ ItemIndex = GET_ITEM_MODEL(13, 392) },
	{ ItemIndex = GET_ITEM_MODEL(13, 393) },
	{ ItemIndex = GET_ITEM_MODEL(13, 394) },
	{ ItemIndex = GET_ITEM_MODEL(13, 395) },
	{ ItemIndex = GET_ITEM_MODEL(13, 396) },
	{ ItemIndex = GET_ITEM_MODEL(13, 397) },
	{ ItemIndex = GET_ITEM_MODEL(13, 398) },
	{ ItemIndex = GET_ITEM_MODEL(13, 399) },
	{ ItemIndex = GET_ITEM_MODEL(13, 400) },
	



--------------------------------------------------------------------------------------------------
--                                       DISABLE EXCELENTE KIT'S                          ----
--------------------------------------------------------------------------------------------------
    { ItemIndex = GET_ITEM_MODEL(15, 400) },
    { ItemIndex = GET_ITEM_MODEL(15, 401) },
    { ItemIndex = GET_ITEM_MODEL(15, 402) },
    { ItemIndex = GET_ITEM_MODEL(15, 403) },
    { ItemIndex = GET_ITEM_MODEL(15, 404) },
    { ItemIndex = GET_ITEM_MODEL(15, 405) },
    { ItemIndex = GET_ITEM_MODEL(15, 406) },
    { ItemIndex = GET_ITEM_MODEL(15, 407) },
    { ItemIndex = GET_ITEM_MODEL(15, 408) },
    { ItemIndex = GET_ITEM_MODEL(15, 409) },
    { ItemIndex = GET_ITEM_MODEL(15, 410) },
    { ItemIndex = GET_ITEM_MODEL(15, 411) },
    { ItemIndex = GET_ITEM_MODEL(15, 412) },
    { ItemIndex = GET_ITEM_MODEL(15, 413) },
    { ItemIndex = GET_ITEM_MODEL(15, 414) },
    { ItemIndex = GET_ITEM_MODEL(15, 415) },
    { ItemIndex = GET_ITEM_MODEL(15, 416) },
    { ItemIndex = GET_ITEM_MODEL(15, 417) },
    { ItemIndex = GET_ITEM_MODEL(15, 418) },
    { ItemIndex = GET_ITEM_MODEL(15, 419) },
    { ItemIndex = GET_ITEM_MODEL(15, 420) },
    { ItemIndex = GET_ITEM_MODEL(15, 421) },
    { ItemIndex = GET_ITEM_MODEL(15, 422) },
    { ItemIndex = GET_ITEM_MODEL(15, 423) },
    { ItemIndex = GET_ITEM_MODEL(15, 424) },
    { ItemIndex = GET_ITEM_MODEL(15, 425) },
    { ItemIndex = GET_ITEM_MODEL(15, 426) },
    { ItemIndex = GET_ITEM_MODEL(15, 427) },
    { ItemIndex = GET_ITEM_MODEL(15, 428) },
    { ItemIndex = GET_ITEM_MODEL(15, 429) },
    { ItemIndex = GET_ITEM_MODEL(15, 430) },
    { ItemIndex = GET_ITEM_MODEL(15, 431) },
    { ItemIndex = GET_ITEM_MODEL(15, 432) },
    { ItemIndex = GET_ITEM_MODEL(15, 433) },
    { ItemIndex = GET_ITEM_MODEL(15, 434) },
    { ItemIndex = GET_ITEM_MODEL(15, 435) },
    { ItemIndex = GET_ITEM_MODEL(15, 436) },
    { ItemIndex = GET_ITEM_MODEL(15, 437) },
    { ItemIndex = GET_ITEM_MODEL(15, 438) },
    { ItemIndex = GET_ITEM_MODEL(15, 439) },
    { ItemIndex = GET_ITEM_MODEL(15, 440) },
    { ItemIndex = GET_ITEM_MODEL(15, 441) },
    { ItemIndex = GET_ITEM_MODEL(15, 442) },
    { ItemIndex = GET_ITEM_MODEL(15, 443) },
    { ItemIndex = GET_ITEM_MODEL(15, 444) },
    { ItemIndex = GET_ITEM_MODEL(15, 445) },
    { ItemIndex = GET_ITEM_MODEL(15, 446) },
    { ItemIndex = GET_ITEM_MODEL(15, 447) },
    { ItemIndex = GET_ITEM_MODEL(15, 448) },
    { ItemIndex = GET_ITEM_MODEL(15, 449) },
    { ItemIndex = GET_ITEM_MODEL(15, 450) },
    { ItemIndex = GET_ITEM_MODEL(15, 451) },
    { ItemIndex = GET_ITEM_MODEL(15, 452) },
    { ItemIndex = GET_ITEM_MODEL(15, 453) },
    { ItemIndex = GET_ITEM_MODEL(15, 454) },
    { ItemIndex = GET_ITEM_MODEL(15, 456) },
    { ItemIndex = GET_ITEM_MODEL(15, 457) },
    { ItemIndex = GET_ITEM_MODEL(15, 458) },
    { ItemIndex = GET_ITEM_MODEL(15, 459) },
    { ItemIndex = GET_ITEM_MODEL(15, 460) },
    { ItemIndex = GET_ITEM_MODEL(15, 461) },
    { ItemIndex = GET_ITEM_MODEL(15, 462) },
    { ItemIndex = GET_ITEM_MODEL(15, 463) },
    { ItemIndex = GET_ITEM_MODEL(15, 464) },
    { ItemIndex = GET_ITEM_MODEL(15, 465) },
    { ItemIndex = GET_ITEM_MODEL(15, 466) },
    { ItemIndex = GET_ITEM_MODEL(15, 467) },
    { ItemIndex = GET_ITEM_MODEL(15, 468) },
    { ItemIndex = GET_ITEM_MODEL(15, 469) },
    { ItemIndex = GET_ITEM_MODEL(15, 470) },
    { ItemIndex = GET_ITEM_MODEL(15, 471) },
    { ItemIndex = GET_ITEM_MODEL(15, 472) },
    { ItemIndex = GET_ITEM_MODEL(15, 473) },
    { ItemIndex = GET_ITEM_MODEL(15, 474) },
    { ItemIndex = GET_ITEM_MODEL(15, 475) },
    { ItemIndex = GET_ITEM_MODEL(15, 476) },
    { ItemIndex = GET_ITEM_MODEL(15, 477) },
    { ItemIndex = GET_ITEM_MODEL(15, 478) },
    { ItemIndex = GET_ITEM_MODEL(15, 479) },
    { ItemIndex = GET_ITEM_MODEL(15, 480) },
    { ItemIndex = GET_ITEM_MODEL(15, 481) },
    { ItemIndex = GET_ITEM_MODEL(15, 482) },
    { ItemIndex = GET_ITEM_MODEL(15, 483) },
    { ItemIndex = GET_ITEM_MODEL(15, 484) },
    { ItemIndex = GET_ITEM_MODEL(15, 485) },
    { ItemIndex = GET_ITEM_MODEL(15, 486) },
    { ItemIndex = GET_ITEM_MODEL(15, 487) },
    { ItemIndex = GET_ITEM_MODEL(15, 488) },
    { ItemIndex = GET_ITEM_MODEL(15, 489) },
    { ItemIndex = GET_ITEM_MODEL(15, 490) },
    { ItemIndex = GET_ITEM_MODEL(15, 491) },
    { ItemIndex = GET_ITEM_MODEL(15, 492) },
    { ItemIndex = GET_ITEM_MODEL(15, 493) },
    { ItemIndex = GET_ITEM_MODEL(15, 494) },
    { ItemIndex = GET_ITEM_MODEL(15, 495) },
    { ItemIndex = GET_ITEM_MODEL(15, 496) },
    { ItemIndex = GET_ITEM_MODEL(15, 497) },
    { ItemIndex = GET_ITEM_MODEL(15, 498) },
    { ItemIndex = GET_ITEM_MODEL(15, 499) },
    { ItemIndex = GET_ITEM_MODEL(15, 500) },
    { ItemIndex = GET_ITEM_MODEL(15, 501) },
    { ItemIndex = GET_ITEM_MODEL(15, 502) },
    { ItemIndex = GET_ITEM_MODEL(15, 503) },
    { ItemIndex = GET_ITEM_MODEL(15, 504) },
    { ItemIndex = GET_ITEM_MODEL(15, 505) },
    { ItemIndex = GET_ITEM_MODEL(15, 506) },
    { ItemIndex = GET_ITEM_MODEL(15, 507) },
    { ItemIndex = GET_ITEM_MODEL(15, 508) },
    { ItemIndex = GET_ITEM_MODEL(15, 509) },
    { ItemIndex = GET_ITEM_MODEL(15, 510) },
    { ItemIndex = GET_ITEM_MODEL(15, 50) },
    { ItemIndex = GET_ITEM_MODEL(15, 51) },
    { ItemIndex = GET_ITEM_MODEL(15, 52) },
    { ItemIndex = GET_ITEM_MODEL(15, 53) },
    { ItemIndex = GET_ITEM_MODEL(15, 54) },
    { ItemIndex = GET_ITEM_MODEL(15, 55) },
    { ItemIndex = GET_ITEM_MODEL(15, 56) },
    { ItemIndex = GET_ITEM_MODEL(15, 57) },
    { ItemIndex = GET_ITEM_MODEL(15, 58) },
    { ItemIndex = GET_ITEM_MODEL(15, 59) },
    { ItemIndex = GET_ITEM_MODEL(15, 60) },
    { ItemIndex = GET_ITEM_MODEL(15, 61) },
    { ItemIndex = GET_ITEM_MODEL(15, 62) },
    { ItemIndex = GET_ITEM_MODEL(15, 63) },
    { ItemIndex = GET_ITEM_MODEL(15, 64) },
    { ItemIndex = GET_ITEM_MODEL(15, 65) },
    { ItemIndex = GET_ITEM_MODEL(15, 66) },
    { ItemIndex = GET_ITEM_MODEL(15, 67) },
    { ItemIndex = GET_ITEM_MODEL(15, 68) },
    { ItemIndex = GET_ITEM_MODEL(15, 69) },
    { ItemIndex = GET_ITEM_MODEL(15, 70) },
    { ItemIndex = GET_ITEM_MODEL(15, 71) },
    { ItemIndex = GET_ITEM_MODEL(15, 72) },
    { ItemIndex = GET_ITEM_MODEL(15, 73) },
    { ItemIndex = GET_ITEM_MODEL(15, 74) },
    { ItemIndex = GET_ITEM_MODEL(15, 75) },
    { ItemIndex = GET_ITEM_MODEL(15, 76) },
    { ItemIndex = GET_ITEM_MODEL(15, 77) },
    { ItemIndex = GET_ITEM_MODEL(15, 78) },
    { ItemIndex = GET_ITEM_MODEL(15, 79) },
    { ItemIndex = GET_ITEM_MODEL(15, 80) },
    { ItemIndex = GET_ITEM_MODEL(15, 81) },
    { ItemIndex = GET_ITEM_MODEL(15, 82) },
    { ItemIndex = GET_ITEM_MODEL(15, 83) },
    { ItemIndex = GET_ITEM_MODEL(15, 84) },
    { ItemIndex = GET_ITEM_MODEL(15, 85) },
    { ItemIndex = GET_ITEM_MODEL(15, 86) },
    { ItemIndex = GET_ITEM_MODEL(15, 87) },
    { ItemIndex = GET_ITEM_MODEL(15, 88) },
    { ItemIndex = GET_ITEM_MODEL(15, 90) },
    { ItemIndex = GET_ITEM_MODEL(15, 91) },
    { ItemIndex = GET_ITEM_MODEL(15, 92) },
    { ItemIndex = GET_ITEM_MODEL(15, 93) },
    { ItemIndex = GET_ITEM_MODEL(15, 94) },
    { ItemIndex = GET_ITEM_MODEL(15, 95) },
    { ItemIndex = GET_ITEM_MODEL(15, 96) },
    { ItemIndex = GET_ITEM_MODEL(15, 97) },
    { ItemIndex = GET_ITEM_MODEL(15, 98) },
    { ItemIndex = GET_ITEM_MODEL(15, 99) },
    { ItemIndex = GET_ITEM_MODEL(15, 100) },
    { ItemIndex = GET_ITEM_MODEL(15, 101) },
    { ItemIndex = GET_ITEM_MODEL(15, 102) },
    { ItemIndex = GET_ITEM_MODEL(15, 103) },
    { ItemIndex = GET_ITEM_MODEL(15, 104) },
    { ItemIndex = GET_ITEM_MODEL(15, 105) },
    { ItemIndex = GET_ITEM_MODEL(15, 106) },
    { ItemIndex = GET_ITEM_MODEL(15, 107) },
    { ItemIndex = GET_ITEM_MODEL(15, 108) },
    { ItemIndex = GET_ITEM_MODEL(15, 109) },
    { ItemIndex = GET_ITEM_MODEL(15, 110) },
    { ItemIndex = GET_ITEM_MODEL(15, 111) },
    { ItemIndex = GET_ITEM_MODEL(15, 112) },
    { ItemIndex = GET_ITEM_MODEL(15, 113) },
    { ItemIndex = GET_ITEM_MODEL(15, 114) },
    { ItemIndex = GET_ITEM_MODEL(15, 115) },
    { ItemIndex = GET_ITEM_MODEL(15, 116) },
    { ItemIndex = GET_ITEM_MODEL(15, 117) },
    { ItemIndex = GET_ITEM_MODEL(15, 118) },
    { ItemIndex = GET_ITEM_MODEL(15, 119) },
    { ItemIndex = GET_ITEM_MODEL(15, 120) },
    { ItemIndex = GET_ITEM_MODEL(15, 121) },
    { ItemIndex = GET_ITEM_MODEL(15, 122) },
    { ItemIndex = GET_ITEM_MODEL(15, 123) },
    { ItemIndex = GET_ITEM_MODEL(15, 124) },
    { ItemIndex = GET_ITEM_MODEL(15, 125) },
    { ItemIndex = GET_ITEM_MODEL(15, 126) },
    { ItemIndex = GET_ITEM_MODEL(15, 127) },
    { ItemIndex = GET_ITEM_MODEL(15, 128) },
    { ItemIndex = GET_ITEM_MODEL(15, 129) },
    { ItemIndex = GET_ITEM_MODEL(15, 130) },
    { ItemIndex = GET_ITEM_MODEL(15, 131) },
    { ItemIndex = GET_ITEM_MODEL(15, 132) },
    { ItemIndex = GET_ITEM_MODEL(15, 133) },
    { ItemIndex = GET_ITEM_MODEL(15, 134) },
    { ItemIndex = GET_ITEM_MODEL(15, 135) },
    { ItemIndex = GET_ITEM_MODEL(15, 136) },
    { ItemIndex = GET_ITEM_MODEL(15, 137) },
    { ItemIndex = GET_ITEM_MODEL(15, 138) },
    { ItemIndex = GET_ITEM_MODEL(15, 139) },
    { ItemIndex = GET_ITEM_MODEL(15, 140) },
    { ItemIndex = GET_ITEM_MODEL(15, 141) },
    { ItemIndex = GET_ITEM_MODEL(15, 142) },
    { ItemIndex = GET_ITEM_MODEL(15, 143) },
    { ItemIndex = GET_ITEM_MODEL(15, 144) },
    { ItemIndex = GET_ITEM_MODEL(15, 145) },
    { ItemIndex = GET_ITEM_MODEL(15, 146) },
    { ItemIndex = GET_ITEM_MODEL(15, 147) },
    { ItemIndex = GET_ITEM_MODEL(15, 148) },
    { ItemIndex = GET_ITEM_MODEL(15, 149) },
    { ItemIndex = GET_ITEM_MODEL(15, 150) },
    { ItemIndex = GET_ITEM_MODEL(15, 151) },
    { ItemIndex = GET_ITEM_MODEL(15, 152) },
    { ItemIndex = GET_ITEM_MODEL(15, 153) },
    { ItemIndex = GET_ITEM_MODEL(15, 154) },
    { ItemIndex = GET_ITEM_MODEL(15, 155) },
    { ItemIndex = GET_ITEM_MODEL(15, 156) },
    { ItemIndex = GET_ITEM_MODEL(15, 157) },
    { ItemIndex = GET_ITEM_MODEL(15, 158) },
    { ItemIndex = GET_ITEM_MODEL(15, 159) },
    { ItemIndex = GET_ITEM_MODEL(15, 160) },
    { ItemIndex = GET_ITEM_MODEL(15, 161) },
    { ItemIndex = GET_ITEM_MODEL(15, 162) },
    { ItemIndex = GET_ITEM_MODEL(15, 163) },
    { ItemIndex = GET_ITEM_MODEL(15, 164) },
    { ItemIndex = GET_ITEM_MODEL(15, 165) },
    { ItemIndex = GET_ITEM_MODEL(15, 166) },
    { ItemIndex = GET_ITEM_MODEL(15, 167) },
    { ItemIndex = GET_ITEM_MODEL(15, 168) },
    { ItemIndex = GET_ITEM_MODEL(15, 169) },
    { ItemIndex = GET_ITEM_MODEL(15, 170) },
    { ItemIndex = GET_ITEM_MODEL(15, 171) },
    { ItemIndex = GET_ITEM_MODEL(15, 172) },
    { ItemIndex = GET_ITEM_MODEL(15, 173) },
    { ItemIndex = GET_ITEM_MODEL(15, 174) },
    { ItemIndex = GET_ITEM_MODEL(15, 175) },
    { ItemIndex = GET_ITEM_MODEL(15, 176) },
    { ItemIndex = GET_ITEM_MODEL(15, 177) },
    { ItemIndex = GET_ITEM_MODEL(15, 178) },
    { ItemIndex = GET_ITEM_MODEL(15, 179) },
    { ItemIndex = GET_ITEM_MODEL(15, 180) },
    { ItemIndex = GET_ITEM_MODEL(15, 181) },
    { ItemIndex = GET_ITEM_MODEL(15, 182) },
    { ItemIndex = GET_ITEM_MODEL(15, 183) },
    { ItemIndex = GET_ITEM_MODEL(15, 184) },
    { ItemIndex = GET_ITEM_MODEL(15, 185) },
    { ItemIndex = GET_ITEM_MODEL(15, 186) },
    { ItemIndex = GET_ITEM_MODEL(15, 187) },
    { ItemIndex = GET_ITEM_MODEL(15, 188) },
    { ItemIndex = GET_ITEM_MODEL(15, 189) },
    { ItemIndex = GET_ITEM_MODEL(15, 190) },
    { ItemIndex = GET_ITEM_MODEL(15, 191) },
    { ItemIndex = GET_ITEM_MODEL(15, 192) },
    { ItemIndex = GET_ITEM_MODEL(15, 193) },
    { ItemIndex = GET_ITEM_MODEL(15, 194) },
    { ItemIndex = GET_ITEM_MODEL(15, 195) },
    { ItemIndex = GET_ITEM_MODEL(15, 196) },
    { ItemIndex = GET_ITEM_MODEL(15, 197) },
    { ItemIndex = GET_ITEM_MODEL(15, 198) },
    { ItemIndex = GET_ITEM_MODEL(15, 199) },
    { ItemIndex = GET_ITEM_MODEL(15, 200) },
    { ItemIndex = GET_ITEM_MODEL(15, 201) },
    { ItemIndex = GET_ITEM_MODEL(15, 202) },
    { ItemIndex = GET_ITEM_MODEL(15, 203) },
    { ItemIndex = GET_ITEM_MODEL(15, 204) },
    { ItemIndex = GET_ITEM_MODEL(15, 205) },
    { ItemIndex = GET_ITEM_MODEL(15, 206) },
    { ItemIndex = GET_ITEM_MODEL(15, 207) },
    { ItemIndex = GET_ITEM_MODEL(15, 208) },
    { ItemIndex = GET_ITEM_MODEL(15, 209) },
    { ItemIndex = GET_ITEM_MODEL(15, 210) },
    { ItemIndex = GET_ITEM_MODEL(15, 211) },
    { ItemIndex = GET_ITEM_MODEL(15, 212) },
    { ItemIndex = GET_ITEM_MODEL(15, 213) },
    { ItemIndex = GET_ITEM_MODEL(15, 214) },
    { ItemIndex = GET_ITEM_MODEL(15, 215) },
    { ItemIndex = GET_ITEM_MODEL(15, 216) },
    { ItemIndex = GET_ITEM_MODEL(15, 217) },
    { ItemIndex = GET_ITEM_MODEL(15, 218) },
    { ItemIndex = GET_ITEM_MODEL(15, 219) },
    { ItemIndex = GET_ITEM_MODEL(15, 220) },
    { ItemIndex = GET_ITEM_MODEL(15, 221) },
    { ItemIndex = GET_ITEM_MODEL(15, 222) },
    { ItemIndex = GET_ITEM_MODEL(15, 223) },
    { ItemIndex = GET_ITEM_MODEL(15, 224) },
    { ItemIndex = GET_ITEM_MODEL(15, 225) },
    { ItemIndex = GET_ITEM_MODEL(15, 226) },
    { ItemIndex = GET_ITEM_MODEL(15, 227) },
    { ItemIndex = GET_ITEM_MODEL(15, 228) },
    { ItemIndex = GET_ITEM_MODEL(15, 229) },
    { ItemIndex = GET_ITEM_MODEL(15, 230) },
    { ItemIndex = GET_ITEM_MODEL(15, 231) },
    { ItemIndex = GET_ITEM_MODEL(15, 232) },


--------------------------------------------------------------------------------------------------
--                                       DISABLE EXCELENTE SHIELDS'S                          ----
--------------------------------------------------------------------------------------------------

    { ItemIndex = GET_ITEM_MODEL(6, 50) },
    { ItemIndex = GET_ITEM_MODEL(6, 51) },
    { ItemIndex = GET_ITEM_MODEL(6, 52) },
    { ItemIndex = GET_ITEM_MODEL(6, 53) },
    { ItemIndex = GET_ITEM_MODEL(6, 54) },
    { ItemIndex = GET_ITEM_MODEL(6, 55) },
    { ItemIndex = GET_ITEM_MODEL(6, 56) },
    { ItemIndex = GET_ITEM_MODEL(6, 57) },
    { ItemIndex = GET_ITEM_MODEL(6, 58) },
    { ItemIndex = GET_ITEM_MODEL(6, 59) },
    { ItemIndex = GET_ITEM_MODEL(6, 60) },
    { ItemIndex = GET_ITEM_MODEL(6, 61) },
    { ItemIndex = GET_ITEM_MODEL(6, 62) },
    { ItemIndex = GET_ITEM_MODEL(6, 63) },
    { ItemIndex = GET_ITEM_MODEL(6, 64) },
    { ItemIndex = GET_ITEM_MODEL(6, 65) },
    { ItemIndex = GET_ITEM_MODEL(6, 66) },
    { ItemIndex = GET_ITEM_MODEL(6, 67) },
    { ItemIndex = GET_ITEM_MODEL(6, 68) },
    { ItemIndex = GET_ITEM_MODEL(6, 69) },
    { ItemIndex = GET_ITEM_MODEL(6, 70) },
    { ItemIndex = GET_ITEM_MODEL(6, 71) },
    { ItemIndex = GET_ITEM_MODEL(6, 72) },
    { ItemIndex = GET_ITEM_MODEL(6, 73) },
    { ItemIndex = GET_ITEM_MODEL(6, 74) },
    { ItemIndex = GET_ITEM_MODEL(6, 75) },
    { ItemIndex = GET_ITEM_MODEL(6, 76) },
    { ItemIndex = GET_ITEM_MODEL(6, 77) },
    { ItemIndex = GET_ITEM_MODEL(6, 78) },
    { ItemIndex = GET_ITEM_MODEL(6, 79) },
    { ItemIndex = GET_ITEM_MODEL(6, 80) },
    { ItemIndex = GET_ITEM_MODEL(6, 81) },
    { ItemIndex = GET_ITEM_MODEL(6, 82) },
    { ItemIndex = GET_ITEM_MODEL(6, 83) },
    { ItemIndex = GET_ITEM_MODEL(6, 84) },
    { ItemIndex = GET_ITEM_MODEL(6, 85) },
    { ItemIndex = GET_ITEM_MODEL(6, 86) },
    { ItemIndex = GET_ITEM_MODEL(6, 87) },
    { ItemIndex = GET_ITEM_MODEL(6, 88) },
    { ItemIndex = GET_ITEM_MODEL(6, 89) },
    { ItemIndex = GET_ITEM_MODEL(6, 90) },
    { ItemIndex = GET_ITEM_MODEL(6, 91) },
    { ItemIndex = GET_ITEM_MODEL(6, 92) },
    { ItemIndex = GET_ITEM_MODEL(6, 93) },
    { ItemIndex = GET_ITEM_MODEL(6, 94) },
    { ItemIndex = GET_ITEM_MODEL(6, 95) },
    { ItemIndex = GET_ITEM_MODEL(6, 96) },
    { ItemIndex = GET_ITEM_MODEL(6, 97) },
    { ItemIndex = GET_ITEM_MODEL(6, 98) },
    { ItemIndex = GET_ITEM_MODEL(6, 99) },
    { ItemIndex = GET_ITEM_MODEL(6, 100) },
    { ItemIndex = GET_ITEM_MODEL(6, 101) },
    { ItemIndex = GET_ITEM_MODEL(6, 102) },
    { ItemIndex = GET_ITEM_MODEL(6, 103) },
    { ItemIndex = GET_ITEM_MODEL(6, 104) },
    { ItemIndex = GET_ITEM_MODEL(6, 105) },
    { ItemIndex = GET_ITEM_MODEL(6, 106) },
    { ItemIndex = GET_ITEM_MODEL(6, 107) },
    { ItemIndex = GET_ITEM_MODEL(6, 108) },
    { ItemIndex = GET_ITEM_MODEL(6, 109) },
    { ItemIndex = GET_ITEM_MODEL(6, 110) },
    { ItemIndex = GET_ITEM_MODEL(6, 111) },
    { ItemIndex = GET_ITEM_MODEL(6, 112) },
    { ItemIndex = GET_ITEM_MODEL(6, 113) },
    { ItemIndex = GET_ITEM_MODEL(6, 114) },
    { ItemIndex = GET_ITEM_MODEL(6, 115) },
    { ItemIndex = GET_ITEM_MODEL(6, 116) },
    { ItemIndex = GET_ITEM_MODEL(6, 117) },
    { ItemIndex = GET_ITEM_MODEL(6, 118) },
    { ItemIndex = GET_ITEM_MODEL(6, 119) },
    { ItemIndex = GET_ITEM_MODEL(6, 120) },
    { ItemIndex = GET_ITEM_MODEL(6, 121) },
    { ItemIndex = GET_ITEM_MODEL(6, 122) },
    { ItemIndex = GET_ITEM_MODEL(6, 123) },
    { ItemIndex = GET_ITEM_MODEL(6, 124) },
    { ItemIndex = GET_ITEM_MODEL(6, 125) },
    { ItemIndex = GET_ITEM_MODEL(6, 126) },
    { ItemIndex = GET_ITEM_MODEL(6, 127) },
    { ItemIndex = GET_ITEM_MODEL(6, 128) },
    { ItemIndex = GET_ITEM_MODEL(6, 129) },
    { ItemIndex = GET_ITEM_MODEL(6, 130) },
    { ItemIndex = GET_ITEM_MODEL(6, 131) },
    { ItemIndex = GET_ITEM_MODEL(6, 132) },
    { ItemIndex = GET_ITEM_MODEL(6, 133) },
    { ItemIndex = GET_ITEM_MODEL(6, 134) },
    { ItemIndex = GET_ITEM_MODEL(6, 135) },
    { ItemIndex = GET_ITEM_MODEL(6, 136) },
    { ItemIndex = GET_ITEM_MODEL(6, 137) },
    { ItemIndex = GET_ITEM_MODEL(6, 138) },
    { ItemIndex = GET_ITEM_MODEL(6, 139) },
    { ItemIndex = GET_ITEM_MODEL(6, 140) },
    --{ ItemIndex = GET_ITEM_MODEL(6, 141) },
    { ItemIndex = GET_ITEM_MODEL(6, 142) },
    { ItemIndex = GET_ITEM_MODEL(6, 143) },
    { ItemIndex = GET_ITEM_MODEL(6, 144) },
    { ItemIndex = GET_ITEM_MODEL(6, 145) },
    { ItemIndex = GET_ITEM_MODEL(6, 146) },
    { ItemIndex = GET_ITEM_MODEL(6, 147) },
    { ItemIndex = GET_ITEM_MODEL(6, 148) },
    { ItemIndex = GET_ITEM_MODEL(6, 149) },
    { ItemIndex = GET_ITEM_MODEL(6, 150) },
    { ItemIndex = GET_ITEM_MODEL(6, 151) },
    { ItemIndex = GET_ITEM_MODEL(6, 152) },
    { ItemIndex = GET_ITEM_MODEL(6, 153) },
    { ItemIndex = GET_ITEM_MODEL(6, 154) },
    { ItemIndex = GET_ITEM_MODEL(6, 155) },
    { ItemIndex = GET_ITEM_MODEL(6, 156) },
    { ItemIndex = GET_ITEM_MODEL(6, 157) },
    { ItemIndex = GET_ITEM_MODEL(6, 158) },
    { ItemIndex = GET_ITEM_MODEL(6, 159) },
    { ItemIndex = GET_ITEM_MODEL(6, 160) },
    { ItemIndex = GET_ITEM_MODEL(6, 161) },
    { ItemIndex = GET_ITEM_MODEL(6, 162) },
    { ItemIndex = GET_ITEM_MODEL(6, 163) },
    { ItemIndex = GET_ITEM_MODEL(6, 164) },
    { ItemIndex = GET_ITEM_MODEL(6, 165) },
    { ItemIndex = GET_ITEM_MODEL(6, 166) },
    { ItemIndex = GET_ITEM_MODEL(6, 167) },
    { ItemIndex = GET_ITEM_MODEL(6, 168) },
    { ItemIndex = GET_ITEM_MODEL(6, 169) },
    { ItemIndex = GET_ITEM_MODEL(6, 170) },
    { ItemIndex = GET_ITEM_MODEL(6, 171) },
    { ItemIndex = GET_ITEM_MODEL(6, 172) },
    { ItemIndex = GET_ITEM_MODEL(6, 173) },
    { ItemIndex = GET_ITEM_MODEL(6, 174) },
    { ItemIndex = GET_ITEM_MODEL(6, 175) },
    { ItemIndex = GET_ITEM_MODEL(6, 176) },
    { ItemIndex = GET_ITEM_MODEL(6, 177) },
    { ItemIndex = GET_ITEM_MODEL(6, 178) },
    { ItemIndex = GET_ITEM_MODEL(6, 179) },
    { ItemIndex = GET_ITEM_MODEL(6, 180) },
    { ItemIndex = GET_ITEM_MODEL(6, 181) },
    { ItemIndex = GET_ITEM_MODEL(6, 182) },
    { ItemIndex = GET_ITEM_MODEL(6, 183) },
    { ItemIndex = GET_ITEM_MODEL(6, 184) },
    { ItemIndex = GET_ITEM_MODEL(6, 185) },
    { ItemIndex = GET_ITEM_MODEL(6, 186) },
    { ItemIndex = GET_ITEM_MODEL(6, 187) },
    { ItemIndex = GET_ITEM_MODEL(6, 188) },
    { ItemIndex = GET_ITEM_MODEL(6, 189) },
    { ItemIndex = GET_ITEM_MODEL(6, 190) },
    { ItemIndex = GET_ITEM_MODEL(6, 191) },
    { ItemIndex = GET_ITEM_MODEL(6, 192) },
    { ItemIndex = GET_ITEM_MODEL(6, 193) },
    { ItemIndex = GET_ITEM_MODEL(6, 194) },
    { ItemIndex = GET_ITEM_MODEL(6, 195) },
    { ItemIndex = GET_ITEM_MODEL(6, 196) },
    { ItemIndex = GET_ITEM_MODEL(6, 197) },
    { ItemIndex = GET_ITEM_MODEL(6, 198) },
    { ItemIndex = GET_ITEM_MODEL(6, 199) },
    { ItemIndex = GET_ITEM_MODEL(6, 200) },
    { ItemIndex = GET_ITEM_MODEL(6, 201) },
    { ItemIndex = GET_ITEM_MODEL(6, 202) },
    { ItemIndex = GET_ITEM_MODEL(6, 203) },
    { ItemIndex = GET_ITEM_MODEL(6, 204) },
    { ItemIndex = GET_ITEM_MODEL(6, 205) },

--------------------------------------------------------------------------------------------------
--                                       DISABLE EXCELENTE SWORDS'S                           ----
--------------------------------------------------------------------------------------------------

    { ItemIndex = GET_ITEM_MODEL(0, 50) },
    { ItemIndex = GET_ITEM_MODEL(0, 51) },
    { ItemIndex = GET_ITEM_MODEL(0, 52) },
    { ItemIndex = GET_ITEM_MODEL(0, 53) },
    { ItemIndex = GET_ITEM_MODEL(0, 54) },
    { ItemIndex = GET_ITEM_MODEL(0, 55) },
    { ItemIndex = GET_ITEM_MODEL(0, 56) },
    { ItemIndex = GET_ITEM_MODEL(0, 57) },
    { ItemIndex = GET_ITEM_MODEL(0, 58) },
    { ItemIndex = GET_ITEM_MODEL(0, 59) },
    { ItemIndex = GET_ITEM_MODEL(0, 60) },
    { ItemIndex = GET_ITEM_MODEL(0, 61) },
    { ItemIndex = GET_ITEM_MODEL(0, 62) },
    { ItemIndex = GET_ITEM_MODEL(0, 63) },
    { ItemIndex = GET_ITEM_MODEL(0, 64) },
    { ItemIndex = GET_ITEM_MODEL(0, 65) },
    { ItemIndex = GET_ITEM_MODEL(0, 66) },
    { ItemIndex = GET_ITEM_MODEL(0, 67) },
    { ItemIndex = GET_ITEM_MODEL(0, 68) },
    { ItemIndex = GET_ITEM_MODEL(0, 69) },
    { ItemIndex = GET_ITEM_MODEL(0, 70) },
    { ItemIndex = GET_ITEM_MODEL(0, 71) },
    { ItemIndex = GET_ITEM_MODEL(0, 72) },
    { ItemIndex = GET_ITEM_MODEL(0, 73) },
    { ItemIndex = GET_ITEM_MODEL(0, 74) },
    { ItemIndex = GET_ITEM_MODEL(0, 75) },
    { ItemIndex = GET_ITEM_MODEL(0, 76) },
    { ItemIndex = GET_ITEM_MODEL(0, 77) },
    { ItemIndex = GET_ITEM_MODEL(0, 78) },
    { ItemIndex = GET_ITEM_MODEL(0, 79) },
    { ItemIndex = GET_ITEM_MODEL(0, 80) },
	
    { ItemIndex = GET_ITEM_MODEL(0, 80	) },
    { ItemIndex = GET_ITEM_MODEL(0, 81	) },
    { ItemIndex = GET_ITEM_MODEL(0, 82	) },
    { ItemIndex = GET_ITEM_MODEL(0, 83	) },
    { ItemIndex = GET_ITEM_MODEL(0, 84	) },
    { ItemIndex = GET_ITEM_MODEL(0, 85	) },
    { ItemIndex = GET_ITEM_MODEL(0, 86	) },
    { ItemIndex = GET_ITEM_MODEL(0, 87	) },
    { ItemIndex = GET_ITEM_MODEL(0, 88	) },
    { ItemIndex = GET_ITEM_MODEL(0, 89	) },
    { ItemIndex = GET_ITEM_MODEL(0, 90	) },
    { ItemIndex = GET_ITEM_MODEL(0, 91	) },
    { ItemIndex = GET_ITEM_MODEL(0, 92	) },
    { ItemIndex = GET_ITEM_MODEL(0, 93	) },
    { ItemIndex = GET_ITEM_MODEL(0, 94	) },
    { ItemIndex = GET_ITEM_MODEL(0, 95	) },
    { ItemIndex = GET_ITEM_MODEL(0, 96	) },
    { ItemIndex = GET_ITEM_MODEL(0, 97	) },
    { ItemIndex = GET_ITEM_MODEL(0, 98	) },
    { ItemIndex = GET_ITEM_MODEL(0, 99	) },
    { ItemIndex = GET_ITEM_MODEL(0, 100) },
    { ItemIndex = GET_ITEM_MODEL(0, 101) },
    { ItemIndex = GET_ITEM_MODEL(0, 102) },
    { ItemIndex = GET_ITEM_MODEL(0, 103) },
    { ItemIndex = GET_ITEM_MODEL(0, 104) },
    { ItemIndex = GET_ITEM_MODEL(0, 105) },
    { ItemIndex = GET_ITEM_MODEL(0, 106) },
    { ItemIndex = GET_ITEM_MODEL(0, 107) },
    { ItemIndex = GET_ITEM_MODEL(0, 108) },
    { ItemIndex = GET_ITEM_MODEL(0, 109) },
    { ItemIndex = GET_ITEM_MODEL(0, 110) },
    { ItemIndex = GET_ITEM_MODEL(0, 111) },
    { ItemIndex = GET_ITEM_MODEL(0, 112) },
    { ItemIndex = GET_ITEM_MODEL(0, 113) },
    { ItemIndex = GET_ITEM_MODEL(0, 114) },
    { ItemIndex = GET_ITEM_MODEL(0, 115) },
    { ItemIndex = GET_ITEM_MODEL(0, 116) },
    { ItemIndex = GET_ITEM_MODEL(0, 117) },
    { ItemIndex = GET_ITEM_MODEL(0, 118) },
    { ItemIndex = GET_ITEM_MODEL(0, 119) },
    { ItemIndex = GET_ITEM_MODEL(0, 120) },
    { ItemIndex = GET_ITEM_MODEL(0, 121) },
    { ItemIndex = GET_ITEM_MODEL(0, 122) },
    { ItemIndex = GET_ITEM_MODEL(0, 123) },
    { ItemIndex = GET_ITEM_MODEL(0, 124) },
    { ItemIndex = GET_ITEM_MODEL(0, 125) },
    { ItemIndex = GET_ITEM_MODEL(0, 126) },
    { ItemIndex = GET_ITEM_MODEL(0, 127) },
    { ItemIndex = GET_ITEM_MODEL(0, 128) },
    { ItemIndex = GET_ITEM_MODEL(0, 129) },
    { ItemIndex = GET_ITEM_MODEL(0, 130) },
    { ItemIndex = GET_ITEM_MODEL(0, 131) },
    { ItemIndex = GET_ITEM_MODEL(0, 132) },
    { ItemIndex = GET_ITEM_MODEL(0, 133) },
    { ItemIndex = GET_ITEM_MODEL(0, 134) },
    { ItemIndex = GET_ITEM_MODEL(0, 135) },
    { ItemIndex = GET_ITEM_MODEL(0, 136) },
    { ItemIndex = GET_ITEM_MODEL(0, 137) },
    { ItemIndex = GET_ITEM_MODEL(0, 138) },
    { ItemIndex = GET_ITEM_MODEL(0, 139) },
    { ItemIndex = GET_ITEM_MODEL(0, 140) },
    { ItemIndex = GET_ITEM_MODEL(0, 141) },
    { ItemIndex = GET_ITEM_MODEL(0, 142) },
    { ItemIndex = GET_ITEM_MODEL(0, 143) },
    { ItemIndex = GET_ITEM_MODEL(0, 144) },
    { ItemIndex = GET_ITEM_MODEL(0, 145) },
    { ItemIndex = GET_ITEM_MODEL(0, 146) },
    { ItemIndex = GET_ITEM_MODEL(0, 147) },
    { ItemIndex = GET_ITEM_MODEL(0, 148) },
    { ItemIndex = GET_ITEM_MODEL(0, 149) },
    { ItemIndex = GET_ITEM_MODEL(0, 150) },
    { ItemIndex = GET_ITEM_MODEL(0, 151) },
    { ItemIndex = GET_ITEM_MODEL(0, 152) },
    { ItemIndex = GET_ITEM_MODEL(0, 153) },
    { ItemIndex = GET_ITEM_MODEL(0, 154) },
    { ItemIndex = GET_ITEM_MODEL(0, 155) },
    { ItemIndex = GET_ITEM_MODEL(0, 156) },
    { ItemIndex = GET_ITEM_MODEL(0, 157) },
    { ItemIndex = GET_ITEM_MODEL(0, 158) },
    { ItemIndex = GET_ITEM_MODEL(0, 159) },
    { ItemIndex = GET_ITEM_MODEL(0, 160) },
    { ItemIndex = GET_ITEM_MODEL(0, 161) },
    { ItemIndex = GET_ITEM_MODEL(0, 162) },
    { ItemIndex = GET_ITEM_MODEL(0, 163) },
    { ItemIndex = GET_ITEM_MODEL(0, 164) },
    { ItemIndex = GET_ITEM_MODEL(0, 165) },
    { ItemIndex = GET_ITEM_MODEL(0, 166) },
    { ItemIndex = GET_ITEM_MODEL(0, 167) },
    { ItemIndex = GET_ITEM_MODEL(0, 168) },
    { ItemIndex = GET_ITEM_MODEL(0, 169) },
    { ItemIndex = GET_ITEM_MODEL(0, 170) },
    { ItemIndex = GET_ITEM_MODEL(0, 171) },
    { ItemIndex = GET_ITEM_MODEL(0, 172) },
    { ItemIndex = GET_ITEM_MODEL(0, 173) },
    { ItemIndex = GET_ITEM_MODEL(0, 174) },
    { ItemIndex = GET_ITEM_MODEL(0, 175) },
    { ItemIndex = GET_ITEM_MODEL(0, 176) },
    { ItemIndex = GET_ITEM_MODEL(0, 177) },
    { ItemIndex = GET_ITEM_MODEL(0, 178) },
    { ItemIndex = GET_ITEM_MODEL(0, 179) },
    { ItemIndex = GET_ITEM_MODEL(0, 180) },
    { ItemIndex = GET_ITEM_MODEL(0, 181) },
    { ItemIndex = GET_ITEM_MODEL(0, 182) },
    { ItemIndex = GET_ITEM_MODEL(0, 183) },
    { ItemIndex = GET_ITEM_MODEL(0, 184) },
    { ItemIndex = GET_ITEM_MODEL(0, 185) },
    { ItemIndex = GET_ITEM_MODEL(0, 186) },
    { ItemIndex = GET_ITEM_MODEL(0, 187) },
    { ItemIndex = GET_ITEM_MODEL(0, 188) },
    { ItemIndex = GET_ITEM_MODEL(0, 189) },
    { ItemIndex = GET_ITEM_MODEL(0, 190) },
    { ItemIndex = GET_ITEM_MODEL(0, 191) },
    { ItemIndex = GET_ITEM_MODEL(0, 192) },
    { ItemIndex = GET_ITEM_MODEL(0, 193) },
    { ItemIndex = GET_ITEM_MODEL(0, 194) },
    { ItemIndex = GET_ITEM_MODEL(0, 195) },
    { ItemIndex = GET_ITEM_MODEL(0, 196) },
    { ItemIndex = GET_ITEM_MODEL(0, 197) },
    { ItemIndex = GET_ITEM_MODEL(0, 198) },
    { ItemIndex = GET_ITEM_MODEL(0, 199) },
    { ItemIndex = GET_ITEM_MODEL(0, 200) },
    { ItemIndex = GET_ITEM_MODEL(0, 201) },
    { ItemIndex = GET_ITEM_MODEL(0, 202) },
    { ItemIndex = GET_ITEM_MODEL(0, 203) },
    { ItemIndex = GET_ITEM_MODEL(0, 204) },
    { ItemIndex = GET_ITEM_MODEL(0, 205) },
    { ItemIndex = GET_ITEM_MODEL(0, 206) },
    { ItemIndex = GET_ITEM_MODEL(0, 207) },
    { ItemIndex = GET_ITEM_MODEL(0, 208) },
    { ItemIndex = GET_ITEM_MODEL(0, 209) },
    { ItemIndex = GET_ITEM_MODEL(0, 210) },
    { ItemIndex = GET_ITEM_MODEL(0, 211) },
    { ItemIndex = GET_ITEM_MODEL(0, 212) },
    { ItemIndex = GET_ITEM_MODEL(0, 213) },
    { ItemIndex = GET_ITEM_MODEL(0, 214) },
    { ItemIndex = GET_ITEM_MODEL(0, 215) },
    { ItemIndex = GET_ITEM_MODEL(0, 216) },
    { ItemIndex = GET_ITEM_MODEL(0, 217) },
    { ItemIndex = GET_ITEM_MODEL(0, 218) },
    { ItemIndex = GET_ITEM_MODEL(0, 219) },
    { ItemIndex = GET_ITEM_MODEL(0, 220) },
    { ItemIndex = GET_ITEM_MODEL(0, 221) },
    { ItemIndex = GET_ITEM_MODEL(0, 222) },
    { ItemIndex = GET_ITEM_MODEL(0, 223) },
    { ItemIndex = GET_ITEM_MODEL(0, 224) },
    { ItemIndex = GET_ITEM_MODEL(0, 225) },
    { ItemIndex = GET_ITEM_MODEL(0, 226) },
    { ItemIndex = GET_ITEM_MODEL(0, 227) },
    { ItemIndex = GET_ITEM_MODEL(0, 228) },
    { ItemIndex = GET_ITEM_MODEL(0, 229) },
    { ItemIndex = GET_ITEM_MODEL(0, 230) },
    { ItemIndex = GET_ITEM_MODEL(0, 231) },
    { ItemIndex = GET_ITEM_MODEL(0, 232) },
    { ItemIndex = GET_ITEM_MODEL(0, 233) },
    { ItemIndex = GET_ITEM_MODEL(0, 234) },
    { ItemIndex = GET_ITEM_MODEL(0, 235) },
    { ItemIndex = GET_ITEM_MODEL(0, 236) },
    { ItemIndex = GET_ITEM_MODEL(0, 237) },
    { ItemIndex = GET_ITEM_MODEL(0, 238) },
    { ItemIndex = GET_ITEM_MODEL(0, 239) },
    { ItemIndex = GET_ITEM_MODEL(0, 240) },
    { ItemIndex = GET_ITEM_MODEL(0, 241) },
    { ItemIndex = GET_ITEM_MODEL(0, 242) },
    { ItemIndex = GET_ITEM_MODEL(0, 243) },
    { ItemIndex = GET_ITEM_MODEL(0, 244) },
    { ItemIndex = GET_ITEM_MODEL(0, 245) },
    { ItemIndex = GET_ITEM_MODEL(0, 246) },
    { ItemIndex = GET_ITEM_MODEL(0, 247) },
    { ItemIndex = GET_ITEM_MODEL(0, 248) },
    { ItemIndex = GET_ITEM_MODEL(0, 249) },
    { ItemIndex = GET_ITEM_MODEL(0, 250) },
    { ItemIndex = GET_ITEM_MODEL(0, 251) },
    { ItemIndex = GET_ITEM_MODEL(0, 252) },
    { ItemIndex = GET_ITEM_MODEL(0, 253) },
    { ItemIndex = GET_ITEM_MODEL(0, 254) },
    { ItemIndex = GET_ITEM_MODEL(0, 255) },
    { ItemIndex = GET_ITEM_MODEL(0, 256) },
    { ItemIndex = GET_ITEM_MODEL(0, 257) },
    { ItemIndex = GET_ITEM_MODEL(0, 258) },
    { ItemIndex = GET_ITEM_MODEL(0, 259) },
    { ItemIndex = GET_ITEM_MODEL(0, 260) },
    { ItemIndex = GET_ITEM_MODEL(0, 261) },
    { ItemIndex = GET_ITEM_MODEL(0, 262) },
    { ItemIndex = GET_ITEM_MODEL(0, 263) },
    { ItemIndex = GET_ITEM_MODEL(0, 264) },
    { ItemIndex = GET_ITEM_MODEL(0, 265) },
    { ItemIndex = GET_ITEM_MODEL(0, 266) },
    { ItemIndex = GET_ITEM_MODEL(0, 267) },
    { ItemIndex = GET_ITEM_MODEL(0, 268) },
    { ItemIndex = GET_ITEM_MODEL(0, 269) },
    { ItemIndex = GET_ITEM_MODEL(0, 270) },
    { ItemIndex = GET_ITEM_MODEL(0, 271) },
    { ItemIndex = GET_ITEM_MODEL(0, 272) },
    { ItemIndex = GET_ITEM_MODEL(0, 276) },
    { ItemIndex = GET_ITEM_MODEL(0, 274) },
    { ItemIndex = GET_ITEM_MODEL(0, 275) },
    { ItemIndex = GET_ITEM_MODEL(0, 276) },
    { ItemIndex = GET_ITEM_MODEL(0, 277) },
    { ItemIndex = GET_ITEM_MODEL(0, 278) },
    { ItemIndex = GET_ITEM_MODEL(0, 279) },
    { ItemIndex = GET_ITEM_MODEL(0, 280) },
    { ItemIndex = GET_ITEM_MODEL(0, 281) },
    { ItemIndex = GET_ITEM_MODEL(0, 282) },
    { ItemIndex = GET_ITEM_MODEL(0, 283) },
    { ItemIndex = GET_ITEM_MODEL(0, 284) },
    { ItemIndex = GET_ITEM_MODEL(0, 285) },
    { ItemIndex = GET_ITEM_MODEL(0, 286) },
    { ItemIndex = GET_ITEM_MODEL(0, 287) },
    { ItemIndex = GET_ITEM_MODEL(0, 288) },
    { ItemIndex = GET_ITEM_MODEL(0, 289) },
    { ItemIndex = GET_ITEM_MODEL(0, 290) },
    { ItemIndex = GET_ITEM_MODEL(0, 291) },
    { ItemIndex = GET_ITEM_MODEL(0, 292) },
    { ItemIndex = GET_ITEM_MODEL(0, 293) },
    { ItemIndex = GET_ITEM_MODEL(0, 294) },
    { ItemIndex = GET_ITEM_MODEL(0, 295) },
    { ItemIndex = GET_ITEM_MODEL(0, 296) },
    { ItemIndex = GET_ITEM_MODEL(0, 297) },
    { ItemIndex = GET_ITEM_MODEL(0, 298) },
    { ItemIndex = GET_ITEM_MODEL(0, 299) },
    { ItemIndex = GET_ITEM_MODEL(0, 300) },
    { ItemIndex = GET_ITEM_MODEL(0, 301) },
    { ItemIndex = GET_ITEM_MODEL(0, 302) },
    { ItemIndex = GET_ITEM_MODEL(0, 303) },
    { ItemIndex = GET_ITEM_MODEL(0, 304) },
    { ItemIndex = GET_ITEM_MODEL(0, 305) },
    { ItemIndex = GET_ITEM_MODEL(0, 306) },
    { ItemIndex = GET_ITEM_MODEL(0, 307) },
    { ItemIndex = GET_ITEM_MODEL(0, 308) },
    { ItemIndex = GET_ITEM_MODEL(0, 309) },
    { ItemIndex = GET_ITEM_MODEL(0, 310) },
    { ItemIndex = GET_ITEM_MODEL(0, 311) },
    { ItemIndex = GET_ITEM_MODEL(0, 312) },
    { ItemIndex = GET_ITEM_MODEL(0, 313) },
    { ItemIndex = GET_ITEM_MODEL(0, 314) },
    { ItemIndex = GET_ITEM_MODEL(0, 315) },
    { ItemIndex = GET_ITEM_MODEL(0, 316) },
    { ItemIndex = GET_ITEM_MODEL(0, 317) },
    { ItemIndex = GET_ITEM_MODEL(0, 318) },
    { ItemIndex = GET_ITEM_MODEL(0, 319) },
    { ItemIndex = GET_ITEM_MODEL(0, 320) },
    { ItemIndex = GET_ITEM_MODEL(0, 321) },
    { ItemIndex = GET_ITEM_MODEL(0, 322) },
    { ItemIndex = GET_ITEM_MODEL(0, 323) },
    { ItemIndex = GET_ITEM_MODEL(0, 324) },
    { ItemIndex = GET_ITEM_MODEL(0, 325) },
    { ItemIndex = GET_ITEM_MODEL(0, 326) },
    { ItemIndex = GET_ITEM_MODEL(0, 327) },
    { ItemIndex = GET_ITEM_MODEL(0, 328) },
    { ItemIndex = GET_ITEM_MODEL(0, 329) },
    { ItemIndex = GET_ITEM_MODEL(0, 330) },
    { ItemIndex = GET_ITEM_MODEL(0, 331) },
    { ItemIndex = GET_ITEM_MODEL(0, 332) },
    { ItemIndex = GET_ITEM_MODEL(0, 333) },
    { ItemIndex = GET_ITEM_MODEL(0, 334) },
    { ItemIndex = GET_ITEM_MODEL(0, 335) },
    { ItemIndex = GET_ITEM_MODEL(0, 336) },
    { ItemIndex = GET_ITEM_MODEL(0, 337) },
    { ItemIndex = GET_ITEM_MODEL(0, 338) },
    { ItemIndex = GET_ITEM_MODEL(0, 339) },
    { ItemIndex = GET_ITEM_MODEL(0, 340) },
    { ItemIndex = GET_ITEM_MODEL(0, 341) },
    { ItemIndex = GET_ITEM_MODEL(0, 342) },
    { ItemIndex = GET_ITEM_MODEL(0, 343) },
    { ItemIndex = GET_ITEM_MODEL(0, 344) },
    { ItemIndex = GET_ITEM_MODEL(0, 345) },
    { ItemIndex = GET_ITEM_MODEL(0, 346) },
    { ItemIndex = GET_ITEM_MODEL(0, 347) },
    { ItemIndex = GET_ITEM_MODEL(0, 348) },
    { ItemIndex = GET_ITEM_MODEL(0, 349) },
    { ItemIndex = GET_ITEM_MODEL(0, 350) },
    { ItemIndex = GET_ITEM_MODEL(0, 351) },
    { ItemIndex = GET_ITEM_MODEL(0, 352) },
    { ItemIndex = GET_ITEM_MODEL(0, 353) },
    { ItemIndex = GET_ITEM_MODEL(0, 354) },
    { ItemIndex = GET_ITEM_MODEL(0, 355) },
    { ItemIndex = GET_ITEM_MODEL(0, 356) },
    { ItemIndex = GET_ITEM_MODEL(0, 357) },
    { ItemIndex = GET_ITEM_MODEL(0, 358) },
    { ItemIndex = GET_ITEM_MODEL(0, 359) },
    { ItemIndex = GET_ITEM_MODEL(0, 360) },
    { ItemIndex = GET_ITEM_MODEL(0, 361) },
    { ItemIndex = GET_ITEM_MODEL(0, 362) },
    { ItemIndex = GET_ITEM_MODEL(0, 363) },
    { ItemIndex = GET_ITEM_MODEL(0, 364) },
    { ItemIndex = GET_ITEM_MODEL(0, 365) },
    { ItemIndex = GET_ITEM_MODEL(0, 366) },
    { ItemIndex = GET_ITEM_MODEL(0, 367) },
    { ItemIndex = GET_ITEM_MODEL(0, 368) },
    { ItemIndex = GET_ITEM_MODEL(0, 369) },
    { ItemIndex = GET_ITEM_MODEL(0, 370) },
    { ItemIndex = GET_ITEM_MODEL(0, 371) },
    { ItemIndex = GET_ITEM_MODEL(0, 372) },
    { ItemIndex = GET_ITEM_MODEL(0, 373) },
    { ItemIndex = GET_ITEM_MODEL(0, 374) },
    { ItemIndex = GET_ITEM_MODEL(0, 375) },
    { ItemIndex = GET_ITEM_MODEL(0, 376) },
    { ItemIndex = GET_ITEM_MODEL(0, 377) },
    { ItemIndex = GET_ITEM_MODEL(0, 378) },
    { ItemIndex = GET_ITEM_MODEL(0, 379) },
    { ItemIndex = GET_ITEM_MODEL(0, 380) },
    { ItemIndex = GET_ITEM_MODEL(0, 381) },
    { ItemIndex = GET_ITEM_MODEL(0, 382) },
    { ItemIndex = GET_ITEM_MODEL(0, 383) },
    { ItemIndex = GET_ITEM_MODEL(0, 384) },
    { ItemIndex = GET_ITEM_MODEL(0, 385) },
    { ItemIndex = GET_ITEM_MODEL(0, 386) },
    { ItemIndex = GET_ITEM_MODEL(0, 387) },
    { ItemIndex = GET_ITEM_MODEL(0, 388) },
    { ItemIndex = GET_ITEM_MODEL(0, 389) },
    { ItemIndex = GET_ITEM_MODEL(0, 390) },
    { ItemIndex = GET_ITEM_MODEL(0, 391) },
    { ItemIndex = GET_ITEM_MODEL(0, 392) },
    { ItemIndex = GET_ITEM_MODEL(0, 393) },
    { ItemIndex = GET_ITEM_MODEL(0, 394) },
    { ItemIndex = GET_ITEM_MODEL(0, 395) },


--------------------------------------------------------------------------------------------------
--                                       DISABLE EXCELENTE SET'S                           ----
--------------------------------------------------------------------------------------------------


    { ItemIndex = GET_ITEM_MODEL(7,  325) },
    { ItemIndex = GET_ITEM_MODEL(8,  325) },
    { ItemIndex = GET_ITEM_MODEL(9,  325) },
    { ItemIndex = GET_ITEM_MODEL(10, 325) },
    { ItemIndex = GET_ITEM_MODEL(11, 325) },

    { ItemIndex = GET_ITEM_MODEL(7,  324) },
    { ItemIndex = GET_ITEM_MODEL(8,  324) },
    { ItemIndex = GET_ITEM_MODEL(9,  324) },
    { ItemIndex = GET_ITEM_MODEL(10, 324) },
    { ItemIndex = GET_ITEM_MODEL(11, 324) },

    { ItemIndex = GET_ITEM_MODEL(7,  323) },
    { ItemIndex = GET_ITEM_MODEL(8,  323) },
    { ItemIndex = GET_ITEM_MODEL(9,  323) },
    { ItemIndex = GET_ITEM_MODEL(10, 323) },
    { ItemIndex = GET_ITEM_MODEL(11, 323) },

    { ItemIndex = GET_ITEM_MODEL(7,  322) },
    { ItemIndex = GET_ITEM_MODEL(8,  322) },
    { ItemIndex = GET_ITEM_MODEL(9,  322) },
    { ItemIndex = GET_ITEM_MODEL(10, 322) },
    { ItemIndex = GET_ITEM_MODEL(11, 322) },

    { ItemIndex = GET_ITEM_MODEL(7,  321) },
    { ItemIndex = GET_ITEM_MODEL(8,  321) },
    { ItemIndex = GET_ITEM_MODEL(9,  321) },
    { ItemIndex = GET_ITEM_MODEL(10, 321) },
    { ItemIndex = GET_ITEM_MODEL(11, 321) },

    { ItemIndex = GET_ITEM_MODEL(7,  320) },
    { ItemIndex = GET_ITEM_MODEL(8,  320) },
    { ItemIndex = GET_ITEM_MODEL(9,  320) },
    { ItemIndex = GET_ITEM_MODEL(10, 320) },
    { ItemIndex = GET_ITEM_MODEL(11, 320) },

    { ItemIndex = GET_ITEM_MODEL(7,  319) },
    { ItemIndex = GET_ITEM_MODEL(8,  319) },
    { ItemIndex = GET_ITEM_MODEL(9,  319) },
    { ItemIndex = GET_ITEM_MODEL(10, 319) },
    { ItemIndex = GET_ITEM_MODEL(11, 319) },

    { ItemIndex = GET_ITEM_MODEL(7,  317) },
    { ItemIndex = GET_ITEM_MODEL(8,  317) },
    { ItemIndex = GET_ITEM_MODEL(9,  317) },
    { ItemIndex = GET_ITEM_MODEL(10, 317) },
    { ItemIndex = GET_ITEM_MODEL(11, 317) },

    { ItemIndex = GET_ITEM_MODEL(7,  316) },
    { ItemIndex = GET_ITEM_MODEL(8,  316) },
    { ItemIndex = GET_ITEM_MODEL(9,  316) },
    { ItemIndex = GET_ITEM_MODEL(10, 316) },
    { ItemIndex = GET_ITEM_MODEL(11, 316) },

    { ItemIndex = GET_ITEM_MODEL(7,  315) },
    { ItemIndex = GET_ITEM_MODEL(8,  315) },
    { ItemIndex = GET_ITEM_MODEL(9,  315) },
    { ItemIndex = GET_ITEM_MODEL(10, 315) },
    { ItemIndex = GET_ITEM_MODEL(11, 315) },

    { ItemIndex = GET_ITEM_MODEL(7,  314) },
    { ItemIndex = GET_ITEM_MODEL(8,  314) },
    { ItemIndex = GET_ITEM_MODEL(9,  314) },
    { ItemIndex = GET_ITEM_MODEL(10, 314) },
    { ItemIndex = GET_ITEM_MODEL(11, 314) },

    { ItemIndex = GET_ITEM_MODEL(7,  313) },
    { ItemIndex = GET_ITEM_MODEL(8,  313) },
    { ItemIndex = GET_ITEM_MODEL(9,  313) },
    { ItemIndex = GET_ITEM_MODEL(10, 313) },
    { ItemIndex = GET_ITEM_MODEL(11, 313) },

    { ItemIndex = GET_ITEM_MODEL(7,  312) },
    { ItemIndex = GET_ITEM_MODEL(8,  312) },
    { ItemIndex = GET_ITEM_MODEL(9,  312) },
    { ItemIndex = GET_ITEM_MODEL(10, 312) },
    { ItemIndex = GET_ITEM_MODEL(11, 312) },

    { ItemIndex = GET_ITEM_MODEL(7,  311) },
    { ItemIndex = GET_ITEM_MODEL(8,  311) },
    { ItemIndex = GET_ITEM_MODEL(9,  311) },
    { ItemIndex = GET_ITEM_MODEL(10, 311) },
    { ItemIndex = GET_ITEM_MODEL(11, 311) },

    { ItemIndex = GET_ITEM_MODEL(7,  310) },
    { ItemIndex = GET_ITEM_MODEL(8,  310) },
    { ItemIndex = GET_ITEM_MODEL(9,  310) },
    { ItemIndex = GET_ITEM_MODEL(10, 310) },
    { ItemIndex = GET_ITEM_MODEL(11, 310) },


    { ItemIndex = GET_ITEM_MODEL(7,  306) },
    { ItemIndex = GET_ITEM_MODEL(8,  306) },
    { ItemIndex = GET_ITEM_MODEL(9,  306) },
    { ItemIndex = GET_ITEM_MODEL(10, 306) },
    { ItemIndex = GET_ITEM_MODEL(11, 306) },


    { ItemIndex = GET_ITEM_MODEL(7,  304) },
    { ItemIndex = GET_ITEM_MODEL(8,  304) },
    { ItemIndex = GET_ITEM_MODEL(9,  304) },
    { ItemIndex = GET_ITEM_MODEL(10, 304) },
    { ItemIndex = GET_ITEM_MODEL(11, 304) },

    { ItemIndex = GET_ITEM_MODEL(7,  303) },
    { ItemIndex = GET_ITEM_MODEL(8,  303) },
    { ItemIndex = GET_ITEM_MODEL(9,  303) },
    { ItemIndex = GET_ITEM_MODEL(10, 303) },
    { ItemIndex = GET_ITEM_MODEL(11, 303) },

    { ItemIndex = GET_ITEM_MODEL(7,  302) },
    { ItemIndex = GET_ITEM_MODEL(8,  302) },
    { ItemIndex = GET_ITEM_MODEL(9,  302) },
    { ItemIndex = GET_ITEM_MODEL(10, 302) },
    { ItemIndex = GET_ITEM_MODEL(11, 302) },

    { ItemIndex = GET_ITEM_MODEL(7,  301) },
    { ItemIndex = GET_ITEM_MODEL(8,  301) },
    { ItemIndex = GET_ITEM_MODEL(9,  301) },
    { ItemIndex = GET_ITEM_MODEL(10, 301) },
    { ItemIndex = GET_ITEM_MODEL(11, 301) },

    { ItemIndex = GET_ITEM_MODEL(7,  300) },
    { ItemIndex = GET_ITEM_MODEL(8,  300) },
    { ItemIndex = GET_ITEM_MODEL(9,  300) },
    { ItemIndex = GET_ITEM_MODEL(10, 300) },
    { ItemIndex = GET_ITEM_MODEL(11, 300) },

    { ItemIndex = GET_ITEM_MODEL(7,  299) },
    { ItemIndex = GET_ITEM_MODEL(8,  299) },
    { ItemIndex = GET_ITEM_MODEL(9,  299) },
    { ItemIndex = GET_ITEM_MODEL(10, 299) },
    { ItemIndex = GET_ITEM_MODEL(11, 299) },

    { ItemIndex = GET_ITEM_MODEL(7,  298) },
    { ItemIndex = GET_ITEM_MODEL(8,  298) },
    { ItemIndex = GET_ITEM_MODEL(9,  298) },
    { ItemIndex = GET_ITEM_MODEL(10, 298) },
    { ItemIndex = GET_ITEM_MODEL(11, 298) },

    { ItemIndex = GET_ITEM_MODEL(7,  297) },
    { ItemIndex = GET_ITEM_MODEL(8,  297) },
    { ItemIndex = GET_ITEM_MODEL(9,  297) },
    { ItemIndex = GET_ITEM_MODEL(10, 297) },
    { ItemIndex = GET_ITEM_MODEL(11, 297) },

    { ItemIndex = GET_ITEM_MODEL(7,  296) },
    { ItemIndex = GET_ITEM_MODEL(8,  296) },
    { ItemIndex = GET_ITEM_MODEL(9,  296) },
    { ItemIndex = GET_ITEM_MODEL(10, 296) },
    { ItemIndex = GET_ITEM_MODEL(11, 296) },

    { ItemIndex = GET_ITEM_MODEL(7,  295) },
    { ItemIndex = GET_ITEM_MODEL(8,  295) },
    { ItemIndex = GET_ITEM_MODEL(9,  295) },
    { ItemIndex = GET_ITEM_MODEL(10, 295) },
    { ItemIndex = GET_ITEM_MODEL(11, 295) },

    { ItemIndex = GET_ITEM_MODEL(7,  294) },
    { ItemIndex = GET_ITEM_MODEL(8,  294) },
    { ItemIndex = GET_ITEM_MODEL(9,  294) },
    { ItemIndex = GET_ITEM_MODEL(10, 294) },
    { ItemIndex = GET_ITEM_MODEL(11, 294) },

    { ItemIndex = GET_ITEM_MODEL(7,  293) },
    { ItemIndex = GET_ITEM_MODEL(8,  293) },
    { ItemIndex = GET_ITEM_MODEL(9,  293) },
    { ItemIndex = GET_ITEM_MODEL(10, 293) },
    { ItemIndex = GET_ITEM_MODEL(11, 293) },

    { ItemIndex = GET_ITEM_MODEL(7,  292) },
    { ItemIndex = GET_ITEM_MODEL(8,  292) },
    { ItemIndex = GET_ITEM_MODEL(9,  292) },
    { ItemIndex = GET_ITEM_MODEL(10, 292) },
    { ItemIndex = GET_ITEM_MODEL(11, 292) },

    { ItemIndex = GET_ITEM_MODEL(7,  291) },
    { ItemIndex = GET_ITEM_MODEL(8,  291) },
    { ItemIndex = GET_ITEM_MODEL(9,  291) },
    { ItemIndex = GET_ITEM_MODEL(10, 291) },
    { ItemIndex = GET_ITEM_MODEL(11, 291) },

    { ItemIndex = GET_ITEM_MODEL(7,  290) },
    { ItemIndex = GET_ITEM_MODEL(8,  290) },
    { ItemIndex = GET_ITEM_MODEL(9,  290) },
    { ItemIndex = GET_ITEM_MODEL(10, 290) },
    { ItemIndex = GET_ITEM_MODEL(11, 290) },


    { ItemIndex = GET_ITEM_MODEL(7,  289) },
    { ItemIndex = GET_ITEM_MODEL(8,  289) },
    { ItemIndex = GET_ITEM_MODEL(9,  289) },
    { ItemIndex = GET_ITEM_MODEL(10, 289) },
    { ItemIndex = GET_ITEM_MODEL(11, 289) },

    { ItemIndex = GET_ITEM_MODEL(7,  288) },
    { ItemIndex = GET_ITEM_MODEL(8,  288) },
    { ItemIndex = GET_ITEM_MODEL(9,  288) },
    { ItemIndex = GET_ITEM_MODEL(10, 288) },
    { ItemIndex = GET_ITEM_MODEL(11, 288) },

	{ ItemIndex = GET_ITEM_MODEL(7,  201) },
    { ItemIndex = GET_ITEM_MODEL(8,  201) },
    { ItemIndex = GET_ITEM_MODEL(9,  201) },
    { ItemIndex = GET_ITEM_MODEL(10, 201) },
    { ItemIndex = GET_ITEM_MODEL(11, 201) },
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  202) },
    { ItemIndex = GET_ITEM_MODEL(8,  202) },
    { ItemIndex = GET_ITEM_MODEL(9,  202) },
    { ItemIndex = GET_ITEM_MODEL(10, 202) },
    { ItemIndex = GET_ITEM_MODEL(11, 202) },	
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  203) },
    { ItemIndex = GET_ITEM_MODEL(8,  203) },
    { ItemIndex = GET_ITEM_MODEL(9,  203) },
    { ItemIndex = GET_ITEM_MODEL(10, 203) },
    { ItemIndex = GET_ITEM_MODEL(11, 203) },	
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  204) },
    { ItemIndex = GET_ITEM_MODEL(8,  204) },
    { ItemIndex = GET_ITEM_MODEL(9,  204) },
    { ItemIndex = GET_ITEM_MODEL(10, 204) },
    { ItemIndex = GET_ITEM_MODEL(11, 204) },	
	
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  205) },
    { ItemIndex = GET_ITEM_MODEL(8,  205) },
    { ItemIndex = GET_ITEM_MODEL(9,  205) },
    { ItemIndex = GET_ITEM_MODEL(10, 205) },
    { ItemIndex = GET_ITEM_MODEL(11, 205) },	
	
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  206) },
    { ItemIndex = GET_ITEM_MODEL(8,  206) },
    { ItemIndex = GET_ITEM_MODEL(9,  206) },
    { ItemIndex = GET_ITEM_MODEL(10, 206) },
    { ItemIndex = GET_ITEM_MODEL(11, 206) },	
	


	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  207) },
    { ItemIndex = GET_ITEM_MODEL(8,  207) },
    { ItemIndex = GET_ITEM_MODEL(9,  207) },
    { ItemIndex = GET_ITEM_MODEL(10, 207) },
    { ItemIndex = GET_ITEM_MODEL(11, 207) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  208) },
    { ItemIndex = GET_ITEM_MODEL(8,  208) },
    { ItemIndex = GET_ITEM_MODEL(9,  208) },
    { ItemIndex = GET_ITEM_MODEL(10, 208) },
    { ItemIndex = GET_ITEM_MODEL(11, 208) },	
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  209) },
    { ItemIndex = GET_ITEM_MODEL(8,  209) },
    { ItemIndex = GET_ITEM_MODEL(9,  209) },
    { ItemIndex = GET_ITEM_MODEL(10, 209) },
    { ItemIndex = GET_ITEM_MODEL(11, 209) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  210) },
    { ItemIndex = GET_ITEM_MODEL(8,  210) },
    { ItemIndex = GET_ITEM_MODEL(9,  210) },
    { ItemIndex = GET_ITEM_MODEL(10, 210) },
    { ItemIndex = GET_ITEM_MODEL(11, 210) },
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  211) },
    { ItemIndex = GET_ITEM_MODEL(8,  211) },
    { ItemIndex = GET_ITEM_MODEL(9,  211) },
    { ItemIndex = GET_ITEM_MODEL(10, 211) },
    { ItemIndex = GET_ITEM_MODEL(11, 211) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  212) },
    { ItemIndex = GET_ITEM_MODEL(8,  212) },
    { ItemIndex = GET_ITEM_MODEL(9,  212) },
    { ItemIndex = GET_ITEM_MODEL(10, 212) },
    { ItemIndex = GET_ITEM_MODEL(11, 212) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  213) },
    { ItemIndex = GET_ITEM_MODEL(8,  213) },
    { ItemIndex = GET_ITEM_MODEL(9,  213) },
    { ItemIndex = GET_ITEM_MODEL(10, 213) },
    { ItemIndex = GET_ITEM_MODEL(11, 213) },


	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  214) },
    { ItemIndex = GET_ITEM_MODEL(8,  214) },
    { ItemIndex = GET_ITEM_MODEL(9,  214) },
    { ItemIndex = GET_ITEM_MODEL(10, 214) },
    { ItemIndex = GET_ITEM_MODEL(11, 214) },
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  215) },
    { ItemIndex = GET_ITEM_MODEL(8,  215) },
    { ItemIndex = GET_ITEM_MODEL(9,  215) },
    { ItemIndex = GET_ITEM_MODEL(10, 215) },
    { ItemIndex = GET_ITEM_MODEL(11, 215) },
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  216) },
    { ItemIndex = GET_ITEM_MODEL(8,  216) },
    { ItemIndex = GET_ITEM_MODEL(9,  216) },
    { ItemIndex = GET_ITEM_MODEL(10, 216) },
    { ItemIndex = GET_ITEM_MODEL(11, 216) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  217) },
    { ItemIndex = GET_ITEM_MODEL(8,  217) },
    { ItemIndex = GET_ITEM_MODEL(9,  217) },
    { ItemIndex = GET_ITEM_MODEL(10, 217) },
    { ItemIndex = GET_ITEM_MODEL(11, 217) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  218) },
    { ItemIndex = GET_ITEM_MODEL(8,  218) },
    { ItemIndex = GET_ITEM_MODEL(9,  218) },
    { ItemIndex = GET_ITEM_MODEL(10, 218) },
    { ItemIndex = GET_ITEM_MODEL(11, 218) },	
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  219) },
    { ItemIndex = GET_ITEM_MODEL(8,  219) },
    { ItemIndex = GET_ITEM_MODEL(9,  219) },
    { ItemIndex = GET_ITEM_MODEL(10, 219) },
    { ItemIndex = GET_ITEM_MODEL(11, 219) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  220) },
    { ItemIndex = GET_ITEM_MODEL(8,  220) },
    { ItemIndex = GET_ITEM_MODEL(9,  220) },
    { ItemIndex = GET_ITEM_MODEL(10, 220) },
    { ItemIndex = GET_ITEM_MODEL(11, 220) },

	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  221) },
    { ItemIndex = GET_ITEM_MODEL(8,  221) },
    { ItemIndex = GET_ITEM_MODEL(9,  221) },
    { ItemIndex = GET_ITEM_MODEL(10, 221) },
    { ItemIndex = GET_ITEM_MODEL(11, 221) },

	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  222) },
    { ItemIndex = GET_ITEM_MODEL(8,  222) },
    { ItemIndex = GET_ITEM_MODEL(9,  222) },
    { ItemIndex = GET_ITEM_MODEL(10, 222) },
    { ItemIndex = GET_ITEM_MODEL(11, 222) },
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  223) },
    { ItemIndex = GET_ITEM_MODEL(8,  223) },
    { ItemIndex = GET_ITEM_MODEL(9,  223) },
    { ItemIndex = GET_ITEM_MODEL(10, 223) },
    { ItemIndex = GET_ITEM_MODEL(11, 223) },
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  224) },
    { ItemIndex = GET_ITEM_MODEL(8,  224) },
    { ItemIndex = GET_ITEM_MODEL(9,  224) },
    { ItemIndex = GET_ITEM_MODEL(10, 224) },
    { ItemIndex = GET_ITEM_MODEL(11, 224) },
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  225) },
    { ItemIndex = GET_ITEM_MODEL(8,  225) },
    { ItemIndex = GET_ITEM_MODEL(9,  225) },
    { ItemIndex = GET_ITEM_MODEL(10, 225) },
    { ItemIndex = GET_ITEM_MODEL(11, 225) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  226) },
    { ItemIndex = GET_ITEM_MODEL(8,  226) },
    { ItemIndex = GET_ITEM_MODEL(9,  226) },
    { ItemIndex = GET_ITEM_MODEL(10, 226) },
    { ItemIndex = GET_ITEM_MODEL(11, 226) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  227) },
    { ItemIndex = GET_ITEM_MODEL(8,  227) },
    { ItemIndex = GET_ITEM_MODEL(9,  227) },
    { ItemIndex = GET_ITEM_MODEL(10, 227) },
    { ItemIndex = GET_ITEM_MODEL(11, 227) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  228) },
    { ItemIndex = GET_ITEM_MODEL(8,  228) },
    { ItemIndex = GET_ITEM_MODEL(9,  228) },
    { ItemIndex = GET_ITEM_MODEL(10, 228) },
    { ItemIndex = GET_ITEM_MODEL(11, 228) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  229) },
    { ItemIndex = GET_ITEM_MODEL(8,  229) },
    { ItemIndex = GET_ITEM_MODEL(9,  229) },
    { ItemIndex = GET_ITEM_MODEL(10, 229) },
    { ItemIndex = GET_ITEM_MODEL(11, 229) },	
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  230) },
    { ItemIndex = GET_ITEM_MODEL(8,  230) },
    { ItemIndex = GET_ITEM_MODEL(9,  230) },
    { ItemIndex = GET_ITEM_MODEL(10, 230) },
    { ItemIndex = GET_ITEM_MODEL(11, 230) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  231) },
    { ItemIndex = GET_ITEM_MODEL(8,  231) },
    { ItemIndex = GET_ITEM_MODEL(9,  231) },
    { ItemIndex = GET_ITEM_MODEL(10, 231) },
    { ItemIndex = GET_ITEM_MODEL(11, 231) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  232) },
    { ItemIndex = GET_ITEM_MODEL(8,  232) },
    { ItemIndex = GET_ITEM_MODEL(9,  232) },
    { ItemIndex = GET_ITEM_MODEL(10, 232) },
    { ItemIndex = GET_ITEM_MODEL(11, 232) },
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  233) },
    { ItemIndex = GET_ITEM_MODEL(8,  233) },
    { ItemIndex = GET_ITEM_MODEL(9,  233) },
    { ItemIndex = GET_ITEM_MODEL(10, 233) },
    { ItemIndex = GET_ITEM_MODEL(11, 233) },

	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  234) },
    { ItemIndex = GET_ITEM_MODEL(8,  234) },
    { ItemIndex = GET_ITEM_MODEL(9,  234) },
    { ItemIndex = GET_ITEM_MODEL(10, 234) },
    { ItemIndex = GET_ITEM_MODEL(11, 234) },
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  235) },
    { ItemIndex = GET_ITEM_MODEL(8,  235) },
    { ItemIndex = GET_ITEM_MODEL(9,  235) },
    { ItemIndex = GET_ITEM_MODEL(10, 235) },
    { ItemIndex = GET_ITEM_MODEL(11, 235) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  236) },
    { ItemIndex = GET_ITEM_MODEL(8,  236) },
    { ItemIndex = GET_ITEM_MODEL(9,  236) },
    { ItemIndex = GET_ITEM_MODEL(10, 236) },
    { ItemIndex = GET_ITEM_MODEL(11, 236) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  237) },
    { ItemIndex = GET_ITEM_MODEL(8,  237) },
    { ItemIndex = GET_ITEM_MODEL(9,  237) },
    { ItemIndex = GET_ITEM_MODEL(10, 237) },
    { ItemIndex = GET_ITEM_MODEL(11, 237) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  238) },
    { ItemIndex = GET_ITEM_MODEL(8,  238) },
    { ItemIndex = GET_ITEM_MODEL(9,  238) },
    { ItemIndex = GET_ITEM_MODEL(10, 238) },
    { ItemIndex = GET_ITEM_MODEL(11, 238) },

	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  239) },
    { ItemIndex = GET_ITEM_MODEL(8,  239) },
    { ItemIndex = GET_ITEM_MODEL(9,  239) },
    { ItemIndex = GET_ITEM_MODEL(10, 239) },
    { ItemIndex = GET_ITEM_MODEL(11, 239) },
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  240) },
    { ItemIndex = GET_ITEM_MODEL(8,  240) },
    { ItemIndex = GET_ITEM_MODEL(9,  240) },
    { ItemIndex = GET_ITEM_MODEL(10, 240) },
    { ItemIndex = GET_ITEM_MODEL(11, 240) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  241) },
    { ItemIndex = GET_ITEM_MODEL(8,  241) },
    { ItemIndex = GET_ITEM_MODEL(9,  241) },
    { ItemIndex = GET_ITEM_MODEL(10, 241) },
    { ItemIndex = GET_ITEM_MODEL(11, 241) },
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  242) },
    { ItemIndex = GET_ITEM_MODEL(8,  242) },
    { ItemIndex = GET_ITEM_MODEL(9,  242) },
    { ItemIndex = GET_ITEM_MODEL(10, 242) },
    { ItemIndex = GET_ITEM_MODEL(11, 242) },

	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  243) },
    { ItemIndex = GET_ITEM_MODEL(8,  243) },
    { ItemIndex = GET_ITEM_MODEL(9,  243) },
    { ItemIndex = GET_ITEM_MODEL(10, 243) },
    { ItemIndex = GET_ITEM_MODEL(11, 243) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  244) },
    { ItemIndex = GET_ITEM_MODEL(8,  244) },
    { ItemIndex = GET_ITEM_MODEL(9,  244) },
    { ItemIndex = GET_ITEM_MODEL(10, 244) },
    { ItemIndex = GET_ITEM_MODEL(11, 244) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  245) },
    { ItemIndex = GET_ITEM_MODEL(8,  245) },
    { ItemIndex = GET_ITEM_MODEL(9,  245) },
    { ItemIndex = GET_ITEM_MODEL(10, 245) },
    { ItemIndex = GET_ITEM_MODEL(11, 245) },

	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  246) },
    { ItemIndex = GET_ITEM_MODEL(8,  246) },
    { ItemIndex = GET_ITEM_MODEL(9,  246) },
    { ItemIndex = GET_ITEM_MODEL(10, 246) },
    { ItemIndex = GET_ITEM_MODEL(11, 246) },
	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  247) },
    { ItemIndex = GET_ITEM_MODEL(8,  247) },
    { ItemIndex = GET_ITEM_MODEL(9,  247) },
    { ItemIndex = GET_ITEM_MODEL(10, 247) },
    { ItemIndex = GET_ITEM_MODEL(11, 247) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  248) },
    { ItemIndex = GET_ITEM_MODEL(8,  248) },
    { ItemIndex = GET_ITEM_MODEL(9,  248) },
    { ItemIndex = GET_ITEM_MODEL(10, 248) },
    { ItemIndex = GET_ITEM_MODEL(11, 248) },

	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  249) },
    { ItemIndex = GET_ITEM_MODEL(8,  249) },
    { ItemIndex = GET_ITEM_MODEL(9,  249) },
    { ItemIndex = GET_ITEM_MODEL(10, 249) },
    { ItemIndex = GET_ITEM_MODEL(11, 249) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  250) },
    { ItemIndex = GET_ITEM_MODEL(8,  250) },
    { ItemIndex = GET_ITEM_MODEL(9,  250) },
    { ItemIndex = GET_ITEM_MODEL(10, 250) },
    { ItemIndex = GET_ITEM_MODEL(11, 250) },
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  251) },
    { ItemIndex = GET_ITEM_MODEL(8,  251) },
    { ItemIndex = GET_ITEM_MODEL(9,  251) },
    { ItemIndex = GET_ITEM_MODEL(10, 251) },
    { ItemIndex = GET_ITEM_MODEL(11, 251) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  252) },
    { ItemIndex = GET_ITEM_MODEL(8,  252) },
    { ItemIndex = GET_ITEM_MODEL(9,  252) },
    { ItemIndex = GET_ITEM_MODEL(10, 252) },
    { ItemIndex = GET_ITEM_MODEL(11, 252) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  253) },
    { ItemIndex = GET_ITEM_MODEL(8,  253) },
    { ItemIndex = GET_ITEM_MODEL(9,  253) },
    { ItemIndex = GET_ITEM_MODEL(10, 253) },
    { ItemIndex = GET_ITEM_MODEL(11, 253) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  254) },
    { ItemIndex = GET_ITEM_MODEL(8,  254) },
    { ItemIndex = GET_ITEM_MODEL(9,  254) },
    { ItemIndex = GET_ITEM_MODEL(10, 254) },
    { ItemIndex = GET_ITEM_MODEL(11, 254) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  255) },
    { ItemIndex = GET_ITEM_MODEL(8,  255) },
    { ItemIndex = GET_ITEM_MODEL(9,  255) },
    { ItemIndex = GET_ITEM_MODEL(10, 255) },
    { ItemIndex = GET_ITEM_MODEL(11, 255) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  256) },
    { ItemIndex = GET_ITEM_MODEL(8,  256) },
    { ItemIndex = GET_ITEM_MODEL(9,  256) },
    { ItemIndex = GET_ITEM_MODEL(10, 256) },
    { ItemIndex = GET_ITEM_MODEL(11, 256) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  257) },
    { ItemIndex = GET_ITEM_MODEL(8,  257) },
    { ItemIndex = GET_ITEM_MODEL(9,  257) },
    { ItemIndex = GET_ITEM_MODEL(10, 257) },
    { ItemIndex = GET_ITEM_MODEL(11, 257) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  258) },
    { ItemIndex = GET_ITEM_MODEL(8,  258) },
    { ItemIndex = GET_ITEM_MODEL(9,  258) },
    { ItemIndex = GET_ITEM_MODEL(10, 258) },
    { ItemIndex = GET_ITEM_MODEL(11, 258) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  259) },
    { ItemIndex = GET_ITEM_MODEL(8,  259) },
    { ItemIndex = GET_ITEM_MODEL(9,  259) },
    { ItemIndex = GET_ITEM_MODEL(10, 259) },
    { ItemIndex = GET_ITEM_MODEL(11, 259) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  260) },
    { ItemIndex = GET_ITEM_MODEL(8,  260) },
    { ItemIndex = GET_ITEM_MODEL(9,  260) },
    { ItemIndex = GET_ITEM_MODEL(10, 260) },
    { ItemIndex = GET_ITEM_MODEL(11, 260) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  261) },
    { ItemIndex = GET_ITEM_MODEL(8,  261) },
    { ItemIndex = GET_ITEM_MODEL(9,  261) },
    { ItemIndex = GET_ITEM_MODEL(10, 261) },
    { ItemIndex = GET_ITEM_MODEL(11, 261) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  262) },
    { ItemIndex = GET_ITEM_MODEL(8,  262) },
    { ItemIndex = GET_ITEM_MODEL(9,  262) },
    { ItemIndex = GET_ITEM_MODEL(10, 262) },
    { ItemIndex = GET_ITEM_MODEL(11, 262) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  263) },
    { ItemIndex = GET_ITEM_MODEL(8,  263) },
    { ItemIndex = GET_ITEM_MODEL(9,  263) },
    { ItemIndex = GET_ITEM_MODEL(10, 263) },
    { ItemIndex = GET_ITEM_MODEL(11, 263) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  264) },
    { ItemIndex = GET_ITEM_MODEL(8,  264) },
    { ItemIndex = GET_ITEM_MODEL(9,  264) },
    { ItemIndex = GET_ITEM_MODEL(10, 264) },
    { ItemIndex = GET_ITEM_MODEL(11, 264) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  265) },
    { ItemIndex = GET_ITEM_MODEL(8,  265) },
    { ItemIndex = GET_ITEM_MODEL(9,  265) },
    { ItemIndex = GET_ITEM_MODEL(10, 265) },
    { ItemIndex = GET_ITEM_MODEL(11, 265) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  266) },
    { ItemIndex = GET_ITEM_MODEL(8,  266) },
    { ItemIndex = GET_ITEM_MODEL(9,  266) },
    { ItemIndex = GET_ITEM_MODEL(10, 266) },
    { ItemIndex = GET_ITEM_MODEL(11, 266) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  267) },
    { ItemIndex = GET_ITEM_MODEL(8,  267) },
    { ItemIndex = GET_ITEM_MODEL(9,  267) },
    { ItemIndex = GET_ITEM_MODEL(10, 267) },
    { ItemIndex = GET_ITEM_MODEL(11, 267) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  268) },
    { ItemIndex = GET_ITEM_MODEL(8,  268) },
    { ItemIndex = GET_ITEM_MODEL(9,  268) },
    { ItemIndex = GET_ITEM_MODEL(10, 268) },
    { ItemIndex = GET_ITEM_MODEL(11, 268) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  269) },
    { ItemIndex = GET_ITEM_MODEL(8,  269) },
    { ItemIndex = GET_ITEM_MODEL(9,  269) },
    { ItemIndex = GET_ITEM_MODEL(10, 269) },
    { ItemIndex = GET_ITEM_MODEL(11, 269) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  270) },
    { ItemIndex = GET_ITEM_MODEL(8,  270) },
    { ItemIndex = GET_ITEM_MODEL(9,  270) },
    { ItemIndex = GET_ITEM_MODEL(10, 270) },
    { ItemIndex = GET_ITEM_MODEL(11, 270) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  271) },
    { ItemIndex = GET_ITEM_MODEL(8,  271) },
    { ItemIndex = GET_ITEM_MODEL(9,  271) },
    { ItemIndex = GET_ITEM_MODEL(10, 271) },
    { ItemIndex = GET_ITEM_MODEL(11, 271) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  272) },
    { ItemIndex = GET_ITEM_MODEL(8,  272) },
    { ItemIndex = GET_ITEM_MODEL(9,  272) },
    { ItemIndex = GET_ITEM_MODEL(10, 272) },
    { ItemIndex = GET_ITEM_MODEL(11, 272) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  273) },
    { ItemIndex = GET_ITEM_MODEL(8,  273) },
    { ItemIndex = GET_ITEM_MODEL(9,  273) },
    { ItemIndex = GET_ITEM_MODEL(10, 273) },
    { ItemIndex = GET_ITEM_MODEL(11, 273) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  274) },
    { ItemIndex = GET_ITEM_MODEL(8,  274) },
    { ItemIndex = GET_ITEM_MODEL(9,  274) },
    { ItemIndex = GET_ITEM_MODEL(10, 274) },
    { ItemIndex = GET_ITEM_MODEL(11, 274) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  275) },
    { ItemIndex = GET_ITEM_MODEL(8,  275) },
    { ItemIndex = GET_ITEM_MODEL(9,  275) },
    { ItemIndex = GET_ITEM_MODEL(10, 275) },
    { ItemIndex = GET_ITEM_MODEL(11, 275) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  276) },
    { ItemIndex = GET_ITEM_MODEL(8,  276) },
    { ItemIndex = GET_ITEM_MODEL(9,  276) },
    { ItemIndex = GET_ITEM_MODEL(10, 276) },
    { ItemIndex = GET_ITEM_MODEL(11, 276) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  277) },
    { ItemIndex = GET_ITEM_MODEL(8,  277) },
    { ItemIndex = GET_ITEM_MODEL(9,  277) },
    { ItemIndex = GET_ITEM_MODEL(10, 277) },
    { ItemIndex = GET_ITEM_MODEL(11, 277) },	
	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  278) },
    { ItemIndex = GET_ITEM_MODEL(8,  278) },
    { ItemIndex = GET_ITEM_MODEL(9,  278) },
    { ItemIndex = GET_ITEM_MODEL(10, 278) },
    { ItemIndex = GET_ITEM_MODEL(11, 278) },	
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  279) },
    { ItemIndex = GET_ITEM_MODEL(8,  279) },
    { ItemIndex = GET_ITEM_MODEL(9,  279) },
    { ItemIndex = GET_ITEM_MODEL(10, 279) },
    { ItemIndex = GET_ITEM_MODEL(11, 279) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  280) },
    { ItemIndex = GET_ITEM_MODEL(8,  280) },
    { ItemIndex = GET_ITEM_MODEL(9,  280) },
    { ItemIndex = GET_ITEM_MODEL(10, 280) },
    { ItemIndex = GET_ITEM_MODEL(11, 280) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  281) },
    { ItemIndex = GET_ITEM_MODEL(8,  281) },
    { ItemIndex = GET_ITEM_MODEL(9,  281) },
    { ItemIndex = GET_ITEM_MODEL(10, 281) },
    { ItemIndex = GET_ITEM_MODEL(11, 281) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  282) },
    { ItemIndex = GET_ITEM_MODEL(8,  282) },
    { ItemIndex = GET_ITEM_MODEL(9,  282) },
    { ItemIndex = GET_ITEM_MODEL(10, 282) },
    { ItemIndex = GET_ITEM_MODEL(11, 282) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  283) },
    { ItemIndex = GET_ITEM_MODEL(8,  283) },
    { ItemIndex = GET_ITEM_MODEL(9,  283) },
    { ItemIndex = GET_ITEM_MODEL(10, 283) },
    { ItemIndex = GET_ITEM_MODEL(11, 283) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  284) },
    { ItemIndex = GET_ITEM_MODEL(8,  284) },
    { ItemIndex = GET_ITEM_MODEL(9,  284) },
    { ItemIndex = GET_ITEM_MODEL(10, 284) },
    { ItemIndex = GET_ITEM_MODEL(11, 284) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  285) },
    { ItemIndex = GET_ITEM_MODEL(8,  285) },
    { ItemIndex = GET_ITEM_MODEL(9,  285) },
    { ItemIndex = GET_ITEM_MODEL(10, 285) },
    { ItemIndex = GET_ITEM_MODEL(11, 285) },
	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  286) },
    { ItemIndex = GET_ITEM_MODEL(8,  286) },
    { ItemIndex = GET_ITEM_MODEL(9,  286) },
    { ItemIndex = GET_ITEM_MODEL(10, 286) },
    { ItemIndex = GET_ITEM_MODEL(11, 286) },	
	
	{ ItemIndex = GET_ITEM_MODEL(7,  287) },
    { ItemIndex = GET_ITEM_MODEL(8,  287) },
    { ItemIndex = GET_ITEM_MODEL(9,  287) },
    { ItemIndex = GET_ITEM_MODEL(10, 287) },
    { ItemIndex = GET_ITEM_MODEL(11, 287) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  327) },
    { ItemIndex = GET_ITEM_MODEL(8,  327) },
    { ItemIndex = GET_ITEM_MODEL(9,  327) },
    { ItemIndex = GET_ITEM_MODEL(10, 327) },
    { ItemIndex = GET_ITEM_MODEL(11, 327) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  328) },
    { ItemIndex = GET_ITEM_MODEL(8,  328) },
    { ItemIndex = GET_ITEM_MODEL(9,  328) },
    { ItemIndex = GET_ITEM_MODEL(10, 328) },
    { ItemIndex = GET_ITEM_MODEL(11, 328) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  329) },
    { ItemIndex = GET_ITEM_MODEL(8,  329) },
    { ItemIndex = GET_ITEM_MODEL(9,  329) },
    { ItemIndex = GET_ITEM_MODEL(10, 329) },
    { ItemIndex = GET_ITEM_MODEL(11, 329) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  330) },
    { ItemIndex = GET_ITEM_MODEL(8,  330) },
    { ItemIndex = GET_ITEM_MODEL(9,  330) },
    { ItemIndex = GET_ITEM_MODEL(10, 330) },
    { ItemIndex = GET_ITEM_MODEL(11, 330) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  331) },
    { ItemIndex = GET_ITEM_MODEL(8,  331) },
    { ItemIndex = GET_ITEM_MODEL(9,  331) },
    { ItemIndex = GET_ITEM_MODEL(10, 331) },
    { ItemIndex = GET_ITEM_MODEL(11, 331) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  332) },
    { ItemIndex = GET_ITEM_MODEL(8,  332) },
    { ItemIndex = GET_ITEM_MODEL(9,  332) },
    { ItemIndex = GET_ITEM_MODEL(10, 332) },
    { ItemIndex = GET_ITEM_MODEL(11, 332) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  333) },
    { ItemIndex = GET_ITEM_MODEL(8,  333) },
    { ItemIndex = GET_ITEM_MODEL(9,  333) },
    { ItemIndex = GET_ITEM_MODEL(10, 333) },
    { ItemIndex = GET_ITEM_MODEL(11, 333) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  334) },
    { ItemIndex = GET_ITEM_MODEL(8,  334) },
    { ItemIndex = GET_ITEM_MODEL(9,  334) },
    { ItemIndex = GET_ITEM_MODEL(10, 334) },
    { ItemIndex = GET_ITEM_MODEL(11, 334) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  335) },
    { ItemIndex = GET_ITEM_MODEL(8,  335) },
    { ItemIndex = GET_ITEM_MODEL(9,  335) },
    { ItemIndex = GET_ITEM_MODEL(10, 335) },
    { ItemIndex = GET_ITEM_MODEL(11, 335) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  336) },
    { ItemIndex = GET_ITEM_MODEL(8,  336) },
    { ItemIndex = GET_ITEM_MODEL(9,  336) },
    { ItemIndex = GET_ITEM_MODEL(10, 336) },
    { ItemIndex = GET_ITEM_MODEL(11, 336) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  337) },
    { ItemIndex = GET_ITEM_MODEL(8,  337) },
    { ItemIndex = GET_ITEM_MODEL(9,  337) },
    { ItemIndex = GET_ITEM_MODEL(10, 337) },
    { ItemIndex = GET_ITEM_MODEL(11, 337) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  338) },
    { ItemIndex = GET_ITEM_MODEL(8,  338) },
    { ItemIndex = GET_ITEM_MODEL(9,  338) },
    { ItemIndex = GET_ITEM_MODEL(10, 338) },
    { ItemIndex = GET_ITEM_MODEL(11, 338) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  339) },
    { ItemIndex = GET_ITEM_MODEL(8,  339) },
    { ItemIndex = GET_ITEM_MODEL(9,  339) },
    { ItemIndex = GET_ITEM_MODEL(10, 339) },
    { ItemIndex = GET_ITEM_MODEL(11, 339) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  340) },
    { ItemIndex = GET_ITEM_MODEL(8,  340) },
    { ItemIndex = GET_ITEM_MODEL(9,  340) },
    { ItemIndex = GET_ITEM_MODEL(10, 340) },
    { ItemIndex = GET_ITEM_MODEL(11, 340) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  341) },
    { ItemIndex = GET_ITEM_MODEL(8,  341) },
    { ItemIndex = GET_ITEM_MODEL(9,  341) },
    { ItemIndex = GET_ITEM_MODEL(10, 341) },
    { ItemIndex = GET_ITEM_MODEL(11, 341) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  342) },
    { ItemIndex = GET_ITEM_MODEL(8,  342) },
    { ItemIndex = GET_ITEM_MODEL(9,  342) },
    { ItemIndex = GET_ITEM_MODEL(10, 342) },
    { ItemIndex = GET_ITEM_MODEL(11, 342) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  343) },
    { ItemIndex = GET_ITEM_MODEL(8,  343) },
    { ItemIndex = GET_ITEM_MODEL(9,  343) },
    { ItemIndex = GET_ITEM_MODEL(10, 343) },
    { ItemIndex = GET_ITEM_MODEL(11, 343) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  344) },
    { ItemIndex = GET_ITEM_MODEL(8,  344) },
    { ItemIndex = GET_ITEM_MODEL(9,  344) },
    { ItemIndex = GET_ITEM_MODEL(10, 344) },
    { ItemIndex = GET_ITEM_MODEL(11, 344) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  345) },
    { ItemIndex = GET_ITEM_MODEL(8,  345) },
    { ItemIndex = GET_ITEM_MODEL(9,  345) },
    { ItemIndex = GET_ITEM_MODEL(10, 345) },
    { ItemIndex = GET_ITEM_MODEL(11, 345) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  346) },
    { ItemIndex = GET_ITEM_MODEL(8,  346) },
    { ItemIndex = GET_ITEM_MODEL(9,  346) },
    { ItemIndex = GET_ITEM_MODEL(10, 346) },
    { ItemIndex = GET_ITEM_MODEL(11, 346) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  347) },
    { ItemIndex = GET_ITEM_MODEL(8,  347) },
    { ItemIndex = GET_ITEM_MODEL(9,  347) },
    { ItemIndex = GET_ITEM_MODEL(10, 347) },
    { ItemIndex = GET_ITEM_MODEL(11, 347) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  348) },
    { ItemIndex = GET_ITEM_MODEL(8,  348) },
    { ItemIndex = GET_ITEM_MODEL(9,  348) },
    { ItemIndex = GET_ITEM_MODEL(10, 348) },
    { ItemIndex = GET_ITEM_MODEL(11, 348) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  349) },
    { ItemIndex = GET_ITEM_MODEL(8,  349) },
    { ItemIndex = GET_ITEM_MODEL(9,  349) },
    { ItemIndex = GET_ITEM_MODEL(10, 349) },
    { ItemIndex = GET_ITEM_MODEL(11, 349) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  350) },
    { ItemIndex = GET_ITEM_MODEL(8,  350) },
    { ItemIndex = GET_ITEM_MODEL(9,  350) },
    { ItemIndex = GET_ITEM_MODEL(10, 350) },
    { ItemIndex = GET_ITEM_MODEL(11, 350) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  351) },
    { ItemIndex = GET_ITEM_MODEL(8,  351) },
    { ItemIndex = GET_ITEM_MODEL(9,  351) },
    { ItemIndex = GET_ITEM_MODEL(10, 351) },
    { ItemIndex = GET_ITEM_MODEL(11, 351) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  352) },
    { ItemIndex = GET_ITEM_MODEL(8,  352) },
    { ItemIndex = GET_ITEM_MODEL(9,  352) },
    { ItemIndex = GET_ITEM_MODEL(10, 352) },
    { ItemIndex = GET_ITEM_MODEL(11, 352) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  353) },
    { ItemIndex = GET_ITEM_MODEL(8,  353) },
    { ItemIndex = GET_ITEM_MODEL(9,  353) },
    { ItemIndex = GET_ITEM_MODEL(10, 353) },
    { ItemIndex = GET_ITEM_MODEL(11, 353) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  354) },
    { ItemIndex = GET_ITEM_MODEL(8,  354) },
    { ItemIndex = GET_ITEM_MODEL(9,  354) },
    { ItemIndex = GET_ITEM_MODEL(10, 354) },
    { ItemIndex = GET_ITEM_MODEL(11, 354) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  355) },
    { ItemIndex = GET_ITEM_MODEL(8,  355) },
    { ItemIndex = GET_ITEM_MODEL(9,  355) },
    { ItemIndex = GET_ITEM_MODEL(10, 355) },
    { ItemIndex = GET_ITEM_MODEL(11, 355) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  356) },
    { ItemIndex = GET_ITEM_MODEL(8,  356) },
    { ItemIndex = GET_ITEM_MODEL(9,  356) },
    { ItemIndex = GET_ITEM_MODEL(10, 356) },
    { ItemIndex = GET_ITEM_MODEL(11, 356) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  357) },
    { ItemIndex = GET_ITEM_MODEL(8,  357) },
    { ItemIndex = GET_ITEM_MODEL(9,  357) },
    { ItemIndex = GET_ITEM_MODEL(10, 357) },
    { ItemIndex = GET_ITEM_MODEL(11, 357) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  357) },
	{ ItemIndex = GET_ITEM_MODEL(8,  357) },
	{ ItemIndex = GET_ITEM_MODEL(9,  357) },
	{ ItemIndex = GET_ITEM_MODEL(10, 357) },
	{ ItemIndex = GET_ITEM_MODEL(11, 357) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  358) },
	{ ItemIndex = GET_ITEM_MODEL(8,  358) },
	{ ItemIndex = GET_ITEM_MODEL(9,  358) },
	{ ItemIndex = GET_ITEM_MODEL(10, 358) },
	{ ItemIndex = GET_ITEM_MODEL(11, 358) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  359) },
	{ ItemIndex = GET_ITEM_MODEL(8,  359) },
	{ ItemIndex = GET_ITEM_MODEL(9,  359) },
	{ ItemIndex = GET_ITEM_MODEL(10, 359) },
	{ ItemIndex = GET_ITEM_MODEL(11, 359) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  360) },
	{ ItemIndex = GET_ITEM_MODEL(8,  360) },
	{ ItemIndex = GET_ITEM_MODEL(9,  360) },
	{ ItemIndex = GET_ITEM_MODEL(10, 360) },
	{ ItemIndex = GET_ITEM_MODEL(11, 360) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  361) },
	{ ItemIndex = GET_ITEM_MODEL(8,  361) },
	{ ItemIndex = GET_ITEM_MODEL(9,  361) },
	{ ItemIndex = GET_ITEM_MODEL(10, 361) },
	{ ItemIndex = GET_ITEM_MODEL(11, 361) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  362) },
	{ ItemIndex = GET_ITEM_MODEL(8,  362) },
	{ ItemIndex = GET_ITEM_MODEL(9,  362) },
	{ ItemIndex = GET_ITEM_MODEL(10, 362) },
	{ ItemIndex = GET_ITEM_MODEL(11, 362) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  363) },
	{ ItemIndex = GET_ITEM_MODEL(8,  363) },
	{ ItemIndex = GET_ITEM_MODEL(9,  363) },
	{ ItemIndex = GET_ITEM_MODEL(10, 363) },
	{ ItemIndex = GET_ITEM_MODEL(11, 363) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  364) },
	{ ItemIndex = GET_ITEM_MODEL(8,  364) },
	{ ItemIndex = GET_ITEM_MODEL(9,  364) },
	{ ItemIndex = GET_ITEM_MODEL(10, 364) },
	{ ItemIndex = GET_ITEM_MODEL(11, 364) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  365) },
	{ ItemIndex = GET_ITEM_MODEL(8,  365) },
	{ ItemIndex = GET_ITEM_MODEL(9,  365) },
	{ ItemIndex = GET_ITEM_MODEL(10, 365) },
	{ ItemIndex = GET_ITEM_MODEL(11, 365) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  366) },
	{ ItemIndex = GET_ITEM_MODEL(8,  366) },
	{ ItemIndex = GET_ITEM_MODEL(9,  366) },
	{ ItemIndex = GET_ITEM_MODEL(10, 366) },
	{ ItemIndex = GET_ITEM_MODEL(11, 366) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  367) },
	{ ItemIndex = GET_ITEM_MODEL(8,  367) },
	{ ItemIndex = GET_ITEM_MODEL(9,  367) },
	{ ItemIndex = GET_ITEM_MODEL(10, 367) },
	{ ItemIndex = GET_ITEM_MODEL(11, 367) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  368) },
	{ ItemIndex = GET_ITEM_MODEL(8,  368) },
	{ ItemIndex = GET_ITEM_MODEL(9,  368) },
	{ ItemIndex = GET_ITEM_MODEL(10, 368) },
	{ ItemIndex = GET_ITEM_MODEL(11, 368) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  369) },
	{ ItemIndex = GET_ITEM_MODEL(8,  369) },
	{ ItemIndex = GET_ITEM_MODEL(9,  369) },
	{ ItemIndex = GET_ITEM_MODEL(10, 369) },
	{ ItemIndex = GET_ITEM_MODEL(11, 369) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  370) },
	{ ItemIndex = GET_ITEM_MODEL(8,  370) },
	{ ItemIndex = GET_ITEM_MODEL(9,  370) },
	{ ItemIndex = GET_ITEM_MODEL(10, 370) },
	{ ItemIndex = GET_ITEM_MODEL(11, 370) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  371) },
	{ ItemIndex = GET_ITEM_MODEL(8,  371) },
	{ ItemIndex = GET_ITEM_MODEL(9,  371) },
	{ ItemIndex = GET_ITEM_MODEL(10, 371) },
	{ ItemIndex = GET_ITEM_MODEL(11, 371) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  372) },
	{ ItemIndex = GET_ITEM_MODEL(8,  372) },
	{ ItemIndex = GET_ITEM_MODEL(9,  372) },
	{ ItemIndex = GET_ITEM_MODEL(10, 372) },
	{ ItemIndex = GET_ITEM_MODEL(11, 372) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  373) },
	{ ItemIndex = GET_ITEM_MODEL(8,  373) },
	{ ItemIndex = GET_ITEM_MODEL(9,  373) },
	{ ItemIndex = GET_ITEM_MODEL(10, 373) },
	{ ItemIndex = GET_ITEM_MODEL(11, 373) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  374) },
	{ ItemIndex = GET_ITEM_MODEL(8,  374) },
	{ ItemIndex = GET_ITEM_MODEL(9,  374) },
	{ ItemIndex = GET_ITEM_MODEL(10, 374) },
	{ ItemIndex = GET_ITEM_MODEL(11, 374) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  375) },
	{ ItemIndex = GET_ITEM_MODEL(8,  375) },
	{ ItemIndex = GET_ITEM_MODEL(9,  375) },
	{ ItemIndex = GET_ITEM_MODEL(10, 375) },
	{ ItemIndex = GET_ITEM_MODEL(11, 375) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  376) },
	{ ItemIndex = GET_ITEM_MODEL(8,  376) },
	{ ItemIndex = GET_ITEM_MODEL(9,  376) },
	{ ItemIndex = GET_ITEM_MODEL(10, 376) },
	{ ItemIndex = GET_ITEM_MODEL(11, 376) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  377) },
	{ ItemIndex = GET_ITEM_MODEL(8,  377) },
	{ ItemIndex = GET_ITEM_MODEL(9,  377) },
	{ ItemIndex = GET_ITEM_MODEL(10, 377) },
	{ ItemIndex = GET_ITEM_MODEL(11, 377) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  378) },
	{ ItemIndex = GET_ITEM_MODEL(8,  378) },
	{ ItemIndex = GET_ITEM_MODEL(9,  378) },
	{ ItemIndex = GET_ITEM_MODEL(10, 378) },
	{ ItemIndex = GET_ITEM_MODEL(11, 378) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  379) },
	{ ItemIndex = GET_ITEM_MODEL(8,  379) },
	{ ItemIndex = GET_ITEM_MODEL(9,  379) },
	{ ItemIndex = GET_ITEM_MODEL(10, 379) },
	{ ItemIndex = GET_ITEM_MODEL(11, 379) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  380) },
	{ ItemIndex = GET_ITEM_MODEL(8,  380) },
	{ ItemIndex = GET_ITEM_MODEL(9,  380) },
	{ ItemIndex = GET_ITEM_MODEL(10, 380) },
	{ ItemIndex = GET_ITEM_MODEL(11, 380) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  381) },
	{ ItemIndex = GET_ITEM_MODEL(8,  381) },
	{ ItemIndex = GET_ITEM_MODEL(9,  381) },
	{ ItemIndex = GET_ITEM_MODEL(10, 381) },
	{ ItemIndex = GET_ITEM_MODEL(11, 381) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  382) },
	{ ItemIndex = GET_ITEM_MODEL(8,  382) },
	{ ItemIndex = GET_ITEM_MODEL(9,  382) },
	{ ItemIndex = GET_ITEM_MODEL(10, 382) },
	{ ItemIndex = GET_ITEM_MODEL(11, 382) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  383) },
	{ ItemIndex = GET_ITEM_MODEL(8,  383) },
	{ ItemIndex = GET_ITEM_MODEL(9,  383) },
	{ ItemIndex = GET_ITEM_MODEL(10, 383) },
	{ ItemIndex = GET_ITEM_MODEL(11, 383) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  384) },
	{ ItemIndex = GET_ITEM_MODEL(8,  384) },
	{ ItemIndex = GET_ITEM_MODEL(9,  384) },
	{ ItemIndex = GET_ITEM_MODEL(10, 384) },
	{ ItemIndex = GET_ITEM_MODEL(11, 384) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  385) },
	{ ItemIndex = GET_ITEM_MODEL(8,  385) },
	{ ItemIndex = GET_ITEM_MODEL(9,  385) },
	{ ItemIndex = GET_ITEM_MODEL(10, 385) },
	{ ItemIndex = GET_ITEM_MODEL(11, 385) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  386) },
	{ ItemIndex = GET_ITEM_MODEL(8,  386) },
	{ ItemIndex = GET_ITEM_MODEL(9,  386) },
	{ ItemIndex = GET_ITEM_MODEL(10, 386) },
	{ ItemIndex = GET_ITEM_MODEL(11, 386) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  387) },
	{ ItemIndex = GET_ITEM_MODEL(8,  387) },
	{ ItemIndex = GET_ITEM_MODEL(9,  387) },
	{ ItemIndex = GET_ITEM_MODEL(10, 387) },
	{ ItemIndex = GET_ITEM_MODEL(11, 387) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  388) },
	{ ItemIndex = GET_ITEM_MODEL(8,  388) },
	{ ItemIndex = GET_ITEM_MODEL(9,  388) },
	{ ItemIndex = GET_ITEM_MODEL(10, 388) },
	{ ItemIndex = GET_ITEM_MODEL(11, 388) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  389) },
	{ ItemIndex = GET_ITEM_MODEL(8,  389) },
	{ ItemIndex = GET_ITEM_MODEL(9,  389) },
	{ ItemIndex = GET_ITEM_MODEL(10, 389) },
	{ ItemIndex = GET_ITEM_MODEL(11, 389) },
	
	{ ItemIndex = GET_ITEM_MODEL(7,  390) },
	{ ItemIndex = GET_ITEM_MODEL(8,  390) },
	{ ItemIndex = GET_ITEM_MODEL(9,  390) },
	{ ItemIndex = GET_ITEM_MODEL(10, 390) },
	{ ItemIndex = GET_ITEM_MODEL(11, 390) },

}

function StartLoadDisableExcellent()

    for i = 1, #DISABLE_EXCELLENT_ITEMS do
        SetDisableExcellent(DISABLE_EXCELLENT_ITEMS[i].ItemIndex)
    end

end

StartLoadDisableExcellent()