Shop_Config = {
    Enabled = true,

    Packet = 79,

    WindowID = 102,

    Texts = {
        ["Eng"] = {
            --[1] = "Alfamu Item Shop",
            [2] = "Escolha um shop para acessar",
            [3] = "Categorias",
            [4] = "Itens",
            [5] = "Shopping Cart",
            [6] = "Selecione um item",
            [7] = "Total:",
            [8] = "Comprar",
            [9] = "Cart Empty",
            [10] = "Build you Item",
            [11] = "Add to Cart",
            [12] = "Update Cart",
            [13] = "Remove from Cart",
            [14] = "Valor Adicional",
            [15] = "Valor Total",
            [16] = "Confirmar",
            [17] = "Maximum amount of excellent options reached",
            [18] = "MU Item Shop not available on PVP Zone",
            [19] = "Insuficient funds to checkout",            
            [20] = "Your purchase was made successfully!",
            [21] = "Your items are available at the Gift Guardian",
            [22] = "We had a problem during the checkout, try again.",
            [23] = "If the error persists, contact administration.",
            [24] = "Carrinho de Compras",
            [25] = "ATENÇÃO:",
            [26] = "As Compras efetuadas",
            [27] = "Não Podem Ser Desfeitas, Tenha Atenção.",			
            [28] = "Resgate Os Itens Comprados no Guardião !",			
            [29] = "Shopping - JcPoints",		
			[30] = "Quantidade:",
			[31] = "Total: %d x %d = %d %s",			
			[32] = "Deseja mesmo confirmar a compra?",			
        },
        ["Por"] = {
            --[1] = "Loja de Itens",
            [2] = "Escolha um shop para acessar",
            [3] = "Categorias",
            [4] = "Itens",
            [5] = "Carrinho de Compras",
            [6] = "Selecione um item",
            [7] = "Total:",
            [8] = "Comprar",
            [9] = "Carrinho vazio",
            [10] = "Configure seu Item",
            [11] = "Adicionar ao Carrinho",
            [12] = "Atualizar Carrinho",
            [13] = "Remover do Carrinho",
            [14] = "Valor Adicional",
            [15] = "Valor Total",
            [16] = "Confirmar",
            [17] = "Máximo de options excelentes atingido",
            [18] = "Loja de itens não disponível em zona PVP",
            [19] = "Saldo insuficiente para finalizar a compra",
            [20] = "Compra realizada com sucesso!",
            [21] = "Seu itens já estao disponíveis no Guardião de Brindes",
            [22] = "Houve um problema ao realizar a compra, tente novamente.",
            [23] = "Se o erro persistir, contate a administração",
            [24] = "Carrinho de Compras",	
            [25] = "ATENÇÃO:",			
            [26] = "As Compras efetuadas",
            [27] = "Não Podem Ser Desfeitas, Tenha Atenção.",			
            [28] = "Resgate Os Itens Comprados no Guardião !",	
            [29] = "Shopping - JcPoints",	
			[30] = "Quantidade:",
			[31] = "Total: %d x %d = %d %s",	
			[32] = "Deseja mesmo confirmar a compra?",	          		
        },
        ["Spn"] = {
            --[1] = "Loja de Itens",
            [2] = "Escolha um shop para acessar",
            [3] = "Categorias",
            [4] = "Itens",
            [5] = "Carrinho de Compras",
            [6] = "Selecione um item",
            [7] = "Total:",
            [8] = "Comprar",
            [9] = "Carrinho vazio",
            [10] = "Configure seu Item",
            [11] = "Adicionar ao Carrinho",
            [12] = "Atualizar Carrinho",
            [13] = "Remover do Carrinho",
            [14] = "Valor Adicional",
            [15] = "Valor Total",
            [16] = "Confirmar",
            [17] = "Máximo de options excelentes atingido",
            [18] = "Loja de itens não disponível em zona PVP",
            [19] = "Saldo insuficiente para finalizar a compra",
            [20] = "Compra realizada com sucesso!",
            [21] = "Seu itens já estao disponíveis no Guardião de Brindes",
            [22] = "Houve um problema ao realizar a compra, tente novamente.",
            [23] = "Se o erro persistir, contate a administração",
            [24] = "Carrinho de Compras",	
            [25] = "ATENÇÃO:",		
            [26] = "As Compras efetuadas",
            [27] = "Não Podem Ser Desfeitas, Tenha Atenção.",			
            [28] = "Resgate Os Itens Comprados no Guardião !",	
            [29] = "Shopping - JcPoints",
			[30] = "Quantidade:",
			[31] = "Total: %d x %d = %d %s",	
			[32] = "Deseja mesmo confirmar a compra?",			
        },
    }

}

return Shop_Config