GuardiaoBrindes_Config = {
	WindowID = 57,

	Packet = 0x34,

	Description = true,

	Images = {
		GB_Chest = 40062,
		GB_Ponto = 40001,
	},

	Texts = {
		["Eng"] = {
			[1] = "Item Guardian",
			[2] = "Hello, I am the Item Guardian!",
			[3] = "Whenever you receive an item",
			[4] = "or a prize via code, I will keep them",
			[5] = "until you can retrieve them with me.",
			[6] = "To retrieve, simply provide me",
			[7] = "your Access Code:",
			[8] = "Access Code",
			[9] = "My Codes",
			[11] = "Select a prize from the list below",
			[12] = "Access",
			[13] = "Access Code",
			[14] = "Code Expiry",
			[15] = "Retrieve",
			[16] = "Select an item from the list below",
			[17] = "Your item has been successfully retrieved!",
			[18] = "This item is no longer available",
			[19] = "Invalid Access Code",
			[20] = "No items available for",
			[21] = "the provided access code",
			[22] = "No more items to retrieve",
			[23] = "You have no items to retrieve",
			[24] = "No space for the item in the inventory",
			[25] = "Click to copy",
			[26] = "Copied!",
			[27] = "Hidden Code",
			[28] = "Confirmar"				
		},

		["Por"] = {
			[1] = "Guardião de Itens",
			[2] = "Olá, eu sou o Guardião de Itens!",
			[3] = "Sempre que você receber um item",
			[4] = "ou prêmio via código, eu os guardarei",
			[5] = "até que você possa retirá-los comigo.",
			[6] = "Para retirar, basta que você me",
			[7] = "informe seu Código de Acesso:",
			[8] = "Acessar Código",
			[9] = "Meus Códigos",
			[11] = "Selecione um brinde na lista abaixo",
			[12] = "Acessar",
			[13] = "Código de Acesso",
			[14] = "Validade do Código",
			[15] = "Retirar",
			[16] = "Selecione um item na lista abaixo",
			[17] = "Seu item foi retirado com sucesso!",
			[18] = "Esse item não está mais disponível",
			[19] = "Código de Acesso inválido",
			[20] = "Nenhum item disponível para",
			[21] = "o código de acesso informado",
			[22] = "Não há mais itens a serem retirados",
			[23] = "Você não possuí itens a serem retirados",
			[24] = "Não há espaço para o item no iventário",
			[25] = "Clique para copiar",
			[26] = "Copiado!",
			[27] = "Código Oculto",
			[28] = "Confirmar"				
		},

		["Spn"] = {
			[1] = "Guardián de Artículos",
			[2] = "¡Hola, soy el Guardián de Artículos!",
			[3] = "Siempre que recibas un artículo",
			[4] = "o un premio a través de un código, los guardaré",
			[5] = "hasta que puedas recuperarlos conmigo.",
			[6] = "Para recuperarlos, simplemente proporciona",
			[7] = "tu Código de Acceso:",
			[8] = "Código de Acceso",
			[9] = "Mis Códigos",
			[11] = "Selecciona un premio de la lista a continuación",
			[12] = "Acceder",
			[13] = "Código de Acceso",
			[14] = "Vencimiento del Código",
			[15] = "Recuperar",
			[16] = "Selecciona un artículo de la lista a continuación",
			[17] = "¡Tu artículo ha sido recuperado con éxito!",
			[18] = "Este artículo ya no está disponible",
			[19] = "Código de Acceso no válido",
			[20] = "No hay artículos disponibles para",
			[21] = "el código de acceso proporcionado",
			[22] = "No hay más artículos para recuperar",
			[23] = "No tienes artículos para recuperar",
			[24] = "No hay espacio para el artículo en el inventario",
			[25] = "Haz clic para copiar",
			[26] = "¡Copiado!",
			[27] = "Código Oculto",
			[28] = "Confirmar"				
		}
	}
}